Repository gardener/landscaper, pull requests merged in 2020-12, with the labels that each got.

#66 fix updating do
  pkg/landscaper/execution/execution.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#67 Add manifest deployer image build and fix vulnerability
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  docs/README.md
  pkg/landscaper/registry/components/cdutils/uri.go
Labels: needs/ok-to-test, needs/review, priority/normal, size/xs

#68 Prevent that installation phase switches too early to Succeeded
  pkg/landscaper/installations/executions/complete.go
  pkg/landscaper/installations/subinstallations/complete.go
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#69 Container deployer private registry
  Dockerfile
  charts/container-deployer/templates/_helpers.tpl
  charts/container-deployer/values.yaml
  examples/deploy-items/33-DeployItem-Container-blueprint.yaml
  go.mod
  go.sum
  hack/install.sh
  pkg/apis/deployer/container/constants.go
  pkg/deployer/container/actuator.go
  pkg/deployer/container/container.go
  pkg/deployer/container/delete.go
  pkg/deployer/container/init/init.go
  pkg/deployer/container/init/options.go
  pkg/deployer/container/pod.go
  pkg/deployer/container/reconcile.go
  pkg/utils/oci/credentials/keyring.go
  vendor/github.com/containerd/containerd/content/helpers.go
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/images/handlers.go
  vendor/github.com/containerd/containerd/images/image.go
  vendor/github.com/containerd/containerd/images/mediatypes.go
  vendor/github.com/containerd/containerd/log/context.go
  vendor/github.com/containerd/containerd/platforms/cpuinfo.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/containerd/containerd/reference/docker/reference.go
  vendor/github.com/containerd/containerd/reference/reference.go
  vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
  vendor/github.com/containerd/containerd/remotes/docker/errcode.go
  vendor/github.com/containerd/containerd/remotes/docker/errdesc.go
  vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
  vendor/github.com/containerd/containerd/remotes/docker/pusher.go
  vendor/github.com/containerd/containerd/remotes/docker/registry.go
  vendor/github.com/containerd/containerd/remotes/docker/resolver.go
  vendor/github.com/containerd/containerd/remotes/docker/scope.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/k8s.io/code-generator/CONTRIBUTING.md
  vendor/k8s.io/code-generator/LICENSE
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/README.md
  vendor/k8s.io/code-generator/SECURITY_CONTACTS
  vendor/k8s.io/code-generator/code-of-conduct.md
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/k8s.io/code-generator/tools.go
  vendor/modules.txt
Labels: area/security, kind/api-change, kind/enhancement, needs/changes, needs/ok-to-test, priority/normal, size/l

#76 Prefix tags with 'v'
  VERSION
Labels: area/open-source, needs/ok-to-test, reviewed/lgtm, size/xs

#81 switch link to cli installation docu
  docs/README.md
  docs/gettingstarted/install-landscaper-cli.md
Labels: needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#80 remove the landscaper-cli
  Makefile
  cmd/landscaper-cli/app/app.go
  cmd/landscaper-cli/app/blueprints/blueprints.go
  cmd/landscaper-cli/app/blueprints/get.go
  cmd/landscaper-cli/app/blueprints/push.go
  cmd/landscaper-cli/app/blueprints/render.go
  cmd/landscaper-cli/app/blueprints/types.go
  cmd/landscaper-cli/app/blueprints/validate.go
  cmd/landscaper-cli/app/componentdescriptor/components.go
  cmd/landscaper-cli/app/componentdescriptor/get.go
  cmd/landscaper-cli/app/componentdescriptor/push.go
  cmd/landscaper-cli/app/constants/constants.go
  cmd/landscaper-cli/app/jsonschema/get.go
  cmd/landscaper-cli/app/jsonschema/jsonschema.go
  cmd/landscaper-cli/app/jsonschema/push.go
  cmd/landscaper-cli/main.go
  docs/tutorials/01-create-simple-blueprint.md
  docs/tutorials/02-simple-import.md
  hack/install-cli.sh
Labels: area/open-source, kind/cleanup, needs/ok-to-test, needs/review, needs/second-opinion, priority/normal, size/xl
