Repository gardener/landscaper, pull requests merged in 2021-07, with the labels that each got.

#237 fix blueprint store directory name length
  pkg/landscaper/blueprints/store.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/3, reviewed/lgtm, size/xs

#234 Improve execution reporting
  apis/core/v1alpha1/constants.go
  pkg/landscaper/controllers/deployitem/controller.go
  pkg/landscaper/controllers/deployitem/reconcile_test.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/execution/reconcile_test.go
  pkg/landscaper/execution/testdata/state/test5/00-execution.yaml
  pkg/landscaper/execution/testdata/state/test5/10-deploy-item.yaml
  test/integration/deployitems/timeouts.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/constants.go
Labels: area/operations, kind/bug, needs/ok-to-test, priority/3, reviewed/lgtm, size/m

#242 improve deployer logging and print config on startup
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/lib/cmd/default.go
  pkg/deployer/lib/controller.go
Labels: area/deployers, needs/ok-to-test, priority/3, reviewed/lgtm, size/s

#247 add deployer owner resource
  apis/core/v1alpha1/doc.go
  apis/core/v1alpha1/register.go
  apis/deployer/core/doc.go
  apis/deployer/core/register.go
  apis/deployer/core/types.go
  apis/deployer/core/v1alpha1/doc.go
  apis/deployer/core/v1alpha1/register.go
  apis/deployer/core/v1alpha1/types.go
  apis/deployer/core/v1alpha1/zz_generated.conversion.go
  apis/deployer/core/v1alpha1/zz_generated.deepcopy.go
  apis/deployer/core/v1alpha1/zz_generated.defaults.go
  apis/deployer/core/zz_generated.deepcopy.go
  apis/hack/generate-schemes/generators/crdgen.go
  apis/hack/generate-schemes/main.go
  apis/openapi/openapi_generated.go
  apis/schema/schema.go
  hack/generate-code.sh
  hack/post-crd-generation.sh
  pkg/deployer/lib/crdresources/deployer.landscaper.gardener.cloud_owners.yaml
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/doc.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/register.go
  vendor/github.com/gardener/landscaper/apis/schema/schema.go
Labels: area/deployers, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, priority/3, size/xl

#250 Fix broken link to blueprint jsonschema definition in documentation
  docs/usage/Blueprints.md
Labels: area/documentation, kind/bug, priority/4, reviewed/lgtm, size/xs

#245 Add tests
  pkg/landscaper/controllers/execution/executions_controller_suite_test.go
  pkg/landscaper/controllers/execution/reconcile_test.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/controllers/installations/reconcile_delete_test.go
  pkg/landscaper/controllers/installations/testdata/state/test3/00-root.yaml
  pkg/landscaper/controllers/installations/testdata/state/test3/10-exec.yaml
  test/utils/controller.go
Labels: kind/test, needs/ok-to-test, needs/review, needs/second-opinion, priority/3, size/m

#251 Patching manifests
  pkg/deployer/helm/ensure.go
  pkg/deployer/manifest/objectapplier.go
  pkg/deployer/manifest/test/e2e_test.go
  pkg/deployer/manifest/test/testdata/05-di.yaml
  pkg/deployer/manifest/test/testdata/06-di-patched.yaml
Labels: area/manifest-deployer, kind/bug, needs/ok-to-test, priority/3, reviewed/lgtm, size/m

#253 Updated local setup documentation
  docs/tutorials/00-local-setup.md
Labels: area/documentation, kind/bug, needs/ok-to-test, priority/4, reviewed/lgtm, reviewed/ok-to-test, size/s

#254 Fix toc link
  docs/technical/deployer_contract.md
Labels: area/documentation, kind/bug, priority/3, reviewed/lgtm, size/xs

#256 Update tutorial simple blueprint
  docs/tutorials/01-create-simple-blueprint.md
Labels: area/documentation, kind/bug, priority/4, reviewed/lgtm, size/xs

#257 Adapted local simple blueprint tutorial for new landscaper-cli commands.
  docs/tutorials/02-local-simple-blueprint.md
Labels: area/documentation, kind/bug, needs/ok-to-test, priority/4, reviewed/lgtm, size/xs

#258 Update tutorial simple import
  docs/tutorials/03-simple-import.md
Labels: area/documentation, kind/bug, needs/ok-to-test, priority/4, reviewed/lgtm, size/xs

#259 Updated tutorial aggregated blueprint
  docs/tutorials/04-aggregated-blueprint.md
Labels: area/documentation, kind/bug, needs/ok-to-test, needs/review, priority/4, size/xs

#262 Update external JSON schema tutorial
  docs/tutorials/03-simple-import.md
  docs/tutorials/05-external-jsonschema.md
  docs/tutorials/resources/echo-server/blueprint/defaultDeployExecution.yaml
  docs/tutorials/resources/external-jsonschema/definitions/component-descriptor.yaml
  docs/tutorials/resources/external-jsonschema/echo-server/blueprint/defaultDeployExecution.yaml
  docs/tutorials/resources/external-jsonschema/installation.yaml
Labels: area/documentation, kind/bug, needs/ok-to-test, priority/4, reviewed/lgtm, size/m

#263 Fix render function
  go.mod
  go.sum
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/subinstallations/helper.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  pkg/landscaper/jsonschema/loader.go
  pkg/landscaper/registry/components/cdutils/cdutils_suite_test.go
  pkg/landscaper/registry/components/cdutils/list.go
  pkg/landscaper/registry/components/cdutils/resolve_test.go
  pkg/landscaper/registry/components/cdutils/spec.go
  pkg/landscaper/registry/components/cdutils/uri.go
  pkg/landscaper/registry/components/cdutils/uri_test.go
  pkg/landscaper/registry/components/cdutils/utils.go
  pkg/utils/landscaper/blueprint.go
  pkg/utils/simplelogger/iologger.go
  vendor/github.com/gardener/component-cli/ociclient/cache/filesystem.go
  vendor/github.com/gardener/component-cli/ociclient/client.go
  vendor/github.com/gardener/component-cli/ociclient/credentials/keyring.go
  vendor/github.com/gardener/image-vector/pkg/overwrite.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, priority/3, size/xl

#218 Add targetlist support
  apis/.schemes/core-v1alpha1-Blueprint.json
  apis/core/types_blueprint.go
  apis/core/types_installation.go
  apis/core/v1alpha1/helper/dataobjects.go
  apis/core/v1alpha1/types_blueprint.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/validation/blueprint.go
  apis/core/validation/blueprint_test.go
  apis/core/validation/helper.go
  apis/core/validation/installation.go
  apis/core/validation/installation_test.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  docs/api-reference/core.md
  docs/usage/Blueprints.md
  docs/usage/Installations.md
  pkg/deployermanagement/controller/deployer_management_reconcile.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_deployerregistrations.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/dataobjects/target.go
  pkg/landscaper/dataobjects/targetlist.go
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/imports/constructor.go
  pkg/landscaper/installations/imports/constructor_test.go
  pkg/landscaper/installations/imports/testdata/state/test9/00-root1.yaml
  pkg/landscaper/installations/imports/testdata/state/test9/00-root2.yaml
  pkg/landscaper/installations/imports/testdata/state/test9/00-root3.yaml
  pkg/landscaper/installations/imports/testdata/state/test9/00-root4.yaml
  pkg/landscaper/installations/imports/testdata/state/test9/11-root-export.yaml
  pkg/landscaper/installations/imports/testdata/state/test9/11-root-ext-import1.yaml
  pkg/landscaper/installations/imports/testdata/state/test9/11-root-ext-import2.yaml
  pkg/landscaper/installations/imports/validation.go
  pkg/landscaper/installations/importstatus.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/testdata/registry/blobs/root-4/blueprint.yaml
  pkg/landscaper/installations/testdata/registry/component-descriptor.yaml
  test/integration/deployers/blueprints/blueprints_tests.go
  test/integration/installations/import-export.go
  test/integration/installations/testdata/00-root-installation.yaml
  test/integration/installations/testdata/10-dummy-secret.yaml
  test/integration/installations/testdata/10-dummy-target.yaml
  test/integration/suite_test.go
  vendor/github.com/gardener/landscaper/apis/core/types_blueprint.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/helper/dataobjects.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_blueprint.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/validation/blueprint.go
  vendor/github.com/gardener/landscaper/apis/core/validation/helper.go
  vendor/github.com/gardener/landscaper/apis/core/validation/installation.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: area/operations, kind/enhancement, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/xl

#269 Fix pod volume permissions to not run as root
  docs/deployer/container.md
  pkg/deployer/container/pod.go
Labels: kind/bug, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/xs

#268 Fix data reconcile trigger for secrets and configmaps
  apis/core/v1alpha1/types_dataobject.go
  pkg/landscaper/dataobjects/dataobject.go
  pkg/landscaper/dataobjects/target.go
  pkg/landscaper/installations/exports/constructor.go
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/imports/outdated_test.go
  pkg/landscaper/installations/imports/validation.go
  pkg/landscaper/installations/operation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_dataobject.go
Labels: area/operations, kind/bug, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/s

#271 make the key in secret and configmap imports optional
  apis/.schemes/core-v1alpha1-Blueprint.json
  apis/core/types_shared.go
  apis/core/v1alpha1/types_shared.go
  apis/core/validation/installation.go
  apis/core/validation/installation_test.go
  apis/openapi/openapi_generated.go
  docs/api-reference/core.md
  docs/usage/Installations.md
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_deployerregistrations.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/helper_test.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/validation/installation.go
Labels: area/usability, kind/enhancement, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/m

#270 Fix nil references
  cmd/landscaper-controller/app/options.go
  pkg/landscaper/blueprints/store.go
Labels: area/robustness, kind/bug, needs/ok-to-test, priority/3, reviewed/lgtm, size/xs
