Repository gardener/landscaper, pull requests merged in 2021-11, with the labels that each got.

#361 move schema generator to new app package
  apis/hack/generate-schemes/app/app.go
  apis/hack/generate-schemes/main.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#363 pass openapi callback as a parameter to the schema generator api
  apis/hack/generate-schemes/app/app.go
  apis/hack/generate-schemes/main.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#365 Fixed typo in doc
  docs/tutorials/01-create-simple-blueprint.md
Labels: area/documentation, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#364 add garbage collection controller for containers
  apis/.schemes/container-v1alpha1-Configuration.json
  apis/deployer/container/constants.go
  apis/deployer/container/types_config.go
  apis/deployer/container/v1alpha1/defaults.go
  apis/deployer/container/v1alpha1/types_config.go
  apis/deployer/container/v1alpha1/zz_generated.conversion.go
  apis/deployer/container/v1alpha1/zz_generated.deepcopy.go
  apis/deployer/container/v1alpha1/zz_generated.defaults.go
  apis/deployer/container/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  pkg/deployer/container/add.go
  pkg/deployer/container/cleanup.go
  pkg/deployer/container/container_delete.go
  pkg/deployer/container/container_reconcile.go
  pkg/deployer/container/container_suite_test.go
  pkg/deployer/container/garbage_collector.go
  pkg/deployer/container/garbage_collector_test.go
  pkg/deployer/container/helper.go
  pkg/deployer/container/pod.go
  pkg/deployer/container/reconciler_deployitem.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/simplelogger/iologger.go
  test/utils/controller.go
  test/utils/envtest/state.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/constants.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/zz_generated.deepcopy.go
Labels: kind/enhancement, kind/test, needs/ok-to-test, needs/second-opinion, size/xl, area/container-deployer, priority/3

#369 ignore all files within vendor directories
  .gitattributes
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, priority/3, area/operations

#367 default deployer context
  apis/.schemes/config-v1alpha1-LandscaperConfiguration.json
  apis/config/types_landscaper_config.go
  apis/config/v1alpha1/defaults.go
  apis/config/v1alpha1/types_landscaper_config.go
  apis/config/v1alpha1/zz_generated.conversion.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  apis/config/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  pkg/deployermanagement/config/deployment.go
  vendor/github.com/gardener/landscaper/apis/config/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/config/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/mock/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/mock/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/mock/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/mock/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/utils/continuousreconcile/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/utils/managedresource/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/utils/readinesschecks/zz_generated.deepcopy.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s, area/deployers, priority/3

#370 add support for namespace creation in the helm deployer
  apis/.schemes/helm-v1alpha1-ProviderConfiguration.json
  apis/deployer/helm/types_provider.go
  apis/deployer/helm/v1alpha1/types_provider.go
  apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  apis/openapi/openapi_generated.go
  docs/deployer/helm.md
  pkg/deployer/container/garbage_collector.go
  pkg/deployer/container/garbage_collector_test.go
  pkg/deployer/helm/chartresolver/chartresolver_suite_test.go
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/helm_suite_test.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/crdmanager/pkg/crdmanager/crdmanager.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, area/helm-deployer, priority/3

#371 fix tag name for controller-utils
  .ci/pipeline_definitions
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, priority/3, area/operations

#373 download component-cli via curl instead of go get
  hack/generate-cd.sh
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, priority/3, area/operations

#375 set default repo context of cd imports
  apis/core/v1alpha1/defaults.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, priority/3

#376 Update install-landscaper-controller.md
  docs/gettingstarted/install-landscaper-controller.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, priority/4

#381 Fix helm chart templating for targetSelector
  charts/container-deployer/templates/_helpers.tpl
  charts/helm-deployer/templates/_helpers.tpl
  charts/manifest-deployer/templates/_helpers.tpl
  charts/mock-deployer/templates/_helpers.tpl
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/deployers, priority/3

#382 Revert "Fix helm chart templating for targetSelector"
  charts/container-deployer/templates/_helpers.tpl
  charts/helm-deployer/templates/_helpers.tpl
  charts/manifest-deployer/templates/_helpers.tpl
  charts/mock-deployer/templates/_helpers.tpl
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#383 Fix agent
  apis/core/v1alpha1/constants.go
  charts/container-deployer/templates/_helpers.tpl
  charts/container-deployer/values.yaml
  charts/helm-deployer/templates/_helpers.tpl
  charts/helm-deployer/values.yaml
  charts/manifest-deployer/templates/_helpers.tpl
  charts/manifest-deployer/values.yaml
  charts/mock-deployer/templates/_helpers.tpl
  cmd/landscaper-controller/app/app.go
  cmd/landscaper-controller/app/app_test.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/constants.go
  pkg/agent/add.go
  pkg/agent/agent.go
  pkg/deployermanagement/config/deployment.go
  pkg/deployermanagement/controller/deployer_management_reconcile.go
  test/integration/deployers/blueprints/blueprints_tests.go
  test/utils/charts.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/constants.go
Labels: kind/bug, kind/test, needs/ok-to-test, needs/review, size/m, area/deployers, priority/2
