Repository gardener/landscaper, pull requests merged in 2021-04, with the labels that each got.

#156 Changed Ingress from v1beta1 to v1 in documentation and examples.
  docs/tutorials/03-simple-import.md
  docs/tutorials/05-external-jsonschema.md
  docs/tutorials/resources/echo-server/blueprint/defaultDeployExecution.yaml
  docs/tutorials/resources/external-jsonschema/echo-server/blueprint/defaultDeployExecution.yaml
  docs/tutorials/resources/local-ingress-nginx/chart/ingress-nginx/templates/NOTES.txt
Labels: area/documentation, kind/cleanup, needs/ok-to-test, priority/5, reviewed/lgtm, size/s

#143 Deploy Item Pickup Timeout Detection
  apis/.schemes/config-v1alpha1-LandscaperConfiguration.json
  apis/config/types_landscaper_config.go
  apis/config/v1alpha1/defaults.go
  apis/config/v1alpha1/types_landscaper_config.go
  apis/config/v1alpha1/zz_generated.conversion.go
  apis/core/constants.go
  apis/core/types_shared.go
  apis/core/v1alpha1/constants.go
  apis/core/v1alpha1/helper/helpers.go
  apis/core/v1alpha1/types_shared.go
  apis/openapi/openapi_generated.go
  charts/landscaper/templates/_helpers.tpl
  charts/landscaper/values.yaml
  cmd/landscaper-controller/app/app.go
  docs/README.md
  docs/technical/deployer_contract.md
  hack/install-landscaper-for-integration-test.sh
  pkg/deployer/container/container_reconcile.go
  pkg/deployer/container/reconciler_deployitem.go
  pkg/deployer/helm/controller.go
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/lib/utils.go
  pkg/deployer/manifest/controller.go
  pkg/deployer/manifest/ensure.go
  pkg/deployer/mock/controller.go
  pkg/landscaper/controllers/deployitem/add.go
  pkg/landscaper/controllers/deployitem/controller.go
  pkg/landscaper/execution/helper.go
  test/integration/deployitems/pickup_timeout.go
  test/integration/deployitems/testdata/00-dummy-installation.yaml
  test/integration/deployitems/testdata/01-mock-installation.yaml
  test/integration/suite_test.go
  test/integration/tutorial/aggregated-blueprint.go
  vendor/github.com/gardener/landscaper/apis/config/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/constants.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/constants.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/helper/helpers.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
Labels: area/operations, kind/enhancement, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/xl

#159 Integration test logging to include start/end timestamps
  test/framework/dump.go
  test/framework/framework.go
Labels: area/testing, kind/enhancement, needs/ok-to-test, priority/4, reviewed/lgtm, size/xs

#161 Fix description of priority identifiers in Github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/pull_request_template.md
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, priority/5, reviewed/lgtm, size/xs

#160 adds default repositoryContext to Landscaper Helm Chart
  charts/landscaper/templates/_helpers.tpl
  charts/landscaper/values.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#154 Changed manifest deployer to use v1alpha2 objects internally
  apis/deployer/manifest/validation/validation.go
  charts/manifest-deployer/templates/_helpers.tpl
  cmd/landscaper-controller/app/app.go
  cmd/manifest-deployer-controller/app/options.go
  docs/tutorials/03-simple-import.md
  docs/tutorials/05-external-jsonschema.md
  docs/tutorials/resources/echo-server/blueprint/defaultDeployExecution.yaml
  docs/tutorials/resources/external-jsonschema/echo-server/blueprint/defaultDeployExecution.yaml
  examples/deploy-items/40-DeployItem-Manifest-secret.yaml
  pkg/deployer/manifest/add.go
  pkg/deployer/manifest/controller.go
  pkg/deployer/manifest/ensure.go
  pkg/deployer/manifest/manifest.go
  pkg/deployer/manifest/objectapplier.go
  pkg/deployer/manifest/test/e2e_test.go
  test/integration/deployers/container_tests.go
  test/integration/deployers/manifest_tests.go
  test/integration/deployers/register.go
  test/testdata/00-DeployItem-Manifest-v1alpha1.yaml
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/validation/validation.go
Labels: area/manifest-deployer, kind/cleanup, kind/test, needs/ok-to-test, priority/4, reviewed/lgtm, size/l

#153 Image vector template functions
  docs/usage/TemplateExecutors.md
  go.sum
  pkg/landscaper/installations/executions/template/gotemplate.go
  pkg/landscaper/installations/executions/template/spifftemplate.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/installations/executions/template/testdata/gotemplate/template-12.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/component-descriptor-12.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/result-12.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/template-12.yaml
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/gardener/component-cli/pkg/imagevector/imagevector.go
  vendor/github.com/gardener/component-cli/pkg/imagevector/overwrite.go
  vendor/github.com/gardener/component-cli/pkg/imagevector/types.go
  vendor/modules.txt
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l

#162 Allows setting Landscaper cluster kubeconfig in all deployer charts and blueprints
  .landscaper/container-deployer/blueprint/blueprint.yaml
  .landscaper/helm-deployer/blueprint/blueprint.yaml
  .landscaper/manifest-deployer/blueprint/blueprint.yaml
  .landscaper/mock-deployer/blueprint/blueprint.yaml
  charts/container-deployer/templates/deployment.yaml
  charts/container-deployer/templates/landscaper-cluster-kubeconfig-secret.yaml
  charts/container-deployer/values.yaml
  charts/helm-deployer/templates/deployment.yaml
  charts/helm-deployer/templates/landscaper-cluster-kubeconfig-secret.yaml
  charts/helm-deployer/values.yaml
  charts/manifest-deployer/templates/deployment.yaml
  charts/manifest-deployer/templates/landscaper-cluster-kubeconfig-secret.yaml
  charts/manifest-deployer/values.yaml
  charts/mock-deployer/templates/deployment.yaml
  charts/mock-deployer/templates/landscaper-cluster-kubeconfig-secret.yaml
  charts/mock-deployer/values.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#166 add nosniff security headers to landscaper admission server
  cmd/landscaper-webhooks-server/app/app.go
Labels: needs/ok-to-test, needs/review, priority/4, size/xs

#168 fixes registry secrets passthrough in deployer helm charts
  charts/container-deployer/templates/_helpers.tpl
  charts/container-deployer/templates/deployment.yaml
  charts/container-deployer/templates/registry-secret.yaml
  charts/helm-deployer/templates/_helpers.tpl
  charts/helm-deployer/templates/deployment.yaml
  charts/helm-deployer/templates/registry-secret.yaml
Labels: kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/xs

#170 depend on publish-trait, rather than on injected steps
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#164 update component-cli lib and simplify ctf build
  .ci/component_descriptor
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/generate-cd.sh
  vendor/github.com/gardener/component-cli/ociclient/client.go
  vendor/github.com/gardener/component-cli/ociclient/credentials/keyring.go
  vendor/github.com/gardener/component-cli/ociclient/oci/ref.go
  vendor/github.com/gardener/component-cli/ociclient/types.go
  vendor/github.com/gardener/component-cli/ociclient/utils.go
  vendor/github.com/opencontainers/distribution-spec/LICENSE
  vendor/github.com/opencontainers/distribution-spec/specs-go/v1/error.go
  vendor/github.com/opencontainers/distribution-spec/specs-go/v1/repository.go
  vendor/github.com/opencontainers/distribution-spec/specs-go/v1/tags.go
  vendor/modules.txt
Labels: area/delivery, needs/ok-to-test, needs/review, priority/3, size/s

#176 updates doc
  charts/landscaper/values.yaml
  docs/usage/Blueprints.md
  examples/components/aggregated/blueprint/blueprint.yaml
  examples/components/external-dns-management/blueprint/blueprint.yaml
  examples/components/nginx-ingress/blueprint/blueprint.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, priority/4, reviewed/lgtm, size/xs

#175 Fix initialisation with default context
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_delete_test.go
  pkg/landscaper/installations/context_test.go
  pkg/landscaper/installations/imports/helper.go
  pkg/landscaper/installations/imports/outdated_test.go
  pkg/landscaper/installations/imports/validation.go
  pkg/landscaper/installations/imports/validation_test.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations_test.go
  pkg/landscaper/installations/testdata/state/test4/00-root.yaml
  pkg/landscaper/installations/testdata/state/test4/01-root.yaml
  test/utils/resources.go
Labels: area/control-plane, kind/bug, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/m

#172 make webhookserver and controller image tags configurable
  Makefile
  apis/core/types_execution.go
  apis/core/v1alpha1/helper/error.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  charts/landscaper/templates/deployment-controller.yaml
  charts/landscaper/templates/deployment-webhooks.yaml
  charts/landscaper/templates/rbac-webhooks.yaml
  charts/landscaper/templates/rolebinding.yaml
  charts/landscaper/templates/service.yaml
  charts/landscaper/templates/serviceaccount.yaml
  charts/landscaper/values.yaml
  docs/api-reference/core.md
  docs/gettingstarted/install-landscaper-controller.md
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/execution/delete.go
  pkg/landscaper/execution/execution.go
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/execution/reconcile_test.go
  test/framework/dump.go
  test/integration/deployitems/pickup_timeout.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/health/health.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/helper/error.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: area/delivery, kind/test, needs/ok-to-test, needs/review, needs/second-opinion, priority/3, size/l

#139 Basic concepts Documentation and first Example
  docs/README_new.md
  docs/level_0/basic_architecture.md
  docs/level_0/basic_concepts.md
  docs/level_0/first_example_component.md
  docs/level_0/first_example_installation.md
  docs/level_0/resources/blueprint/blueprint.yaml
  docs/level_0/resources/blueprint/deploy-execution-nginx.yaml
  docs/level_0/resources/component-descriptor.yaml
  docs/level_0/resources/installation.yaml
  docs/motivation/motivation.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#183 add the possibility to specify the kubeconfig target from a secret
  apis/core/v1alpha1/types_target.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  docs/README.md
  docs/api-reference/core.md
  docs/technical/target_types.md
  docs/technical/types.md
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/helm.go
  pkg/deployer/helm/helm_suite_test.go
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/lib/utils.go
  pkg/deployer/manifest/ensure.go
  pkg/deployer/manifest/manifest.go
  pkg/deployer/manifest/manifest_suite_test.go
  pkg/deployer/manifest/test/e2e_test.go
  pkg/utils/builders.go
  test/utils/envtest/state.go
  test/utils/resources.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_target.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
Labels: area/deployers, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, priority/3, size/l

#182 add new component overwrite crd
  apis/core/register.go
  apis/core/types_component_overwrite.go
  apis/core/v1alpha1/register.go
  apis/core/v1alpha1/types_component_overwrite.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/validation/component_overwrite.go
  apis/core/validation/component_overwrite_test.go
  apis/core/validation/installation_test.go
  apis/core/validation/validation_suite_test.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  cmd/landscaper-controller/app/app.go
  cmd/landscaper-webhooks-server/app/options.go
  docs/README.md
  docs/api-reference/core.md
  docs/usage/ComponentOverwrites.md
  examples/60-Example-ComponentOverwrite.yaml
  pkg/landscaper/controllers/componentoverwrites/add.go
  pkg/landscaper/controllers/componentoverwrites/componentoverwrites_controller_suite_test.go
  pkg/landscaper/controllers/componentoverwrites/controller.go
  pkg/landscaper/controllers/installations/add.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/controllers/installations/reconcile_test.go
  pkg/landscaper/controllers/installations/registry.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_componentoverwrites.yaml
  pkg/landscaper/registry/componentoverwrites/component_overwrites.go
  pkg/utils/webhook/webhook.go
  vendor/github.com/gardener/landscaper/apis/core/register.go
  vendor/github.com/gardener/landscaper/apis/core/types_component_overwrite.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/register.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_component_overwrite.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/validation/component_overwrite.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, priority/3, size/xl

#188 fix landscaper helm chart
  charts/landscaper/values.yaml
Labels: kind/bug, needs/ok-to-test, needs/review, priority/3, size/xs

#181 Refactor helm/manifest deployer api
  apis/.schemes/helm-v1alpha1-ProviderConfiguration.json
  apis/.schemes/manifest-v1alpha1-ProviderConfiguration.json
  apis/.schemes/manifest-v1alpha2-ProviderConfiguration.json
  apis/deployer/helm/types_provider.go
  apis/deployer/helm/v1alpha1/defaults.go
  apis/deployer/helm/v1alpha1/types_provider.go
  apis/deployer/helm/v1alpha1/validation/validation.go
  apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  apis/deployer/helm/v1alpha1/zz_generated.deepcopy.go
  apis/deployer/helm/zz_generated.deepcopy.go
  apis/deployer/manifest/types_provider.go
  apis/deployer/manifest/v1alpha1/conversions.go
  apis/deployer/manifest/v1alpha1/conversions_test.go
  apis/deployer/manifest/v1alpha1/defaults.go
  apis/deployer/manifest/v1alpha1/types_provider.go
  apis/deployer/manifest/v1alpha1/zz_generated.conversion.go
  apis/deployer/manifest/v1alpha1/zz_generated.deepcopy.go
  apis/deployer/manifest/v1alpha2/defaults.go
  apis/deployer/manifest/v1alpha2/types_provider.go
  apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
  apis/deployer/manifest/v1alpha2/zz_generated.deepcopy.go
  apis/deployer/manifest/validation/validation.go
  apis/deployer/manifest/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/manifest/ensure.go
  pkg/deployer/manifest/objectapplier.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/validation/validation.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/conversions.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/defaults.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/validation/validation.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/zz_generated.deepcopy.go
Labels: area/helm-deployer, area/manifest-deployer, kind/api-change, kind/cleanup, kind/test, needs/ok-to-test, priority/3, reviewed/lgtm, size/l
