Repository gardener/landscaper, pull requests merged in 2021-09, with the labels that each got.

#300 fix ident of imports in docu
  docs/deployer/container.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#302 use semantic names for the pull secrets mounted in the container deployer
  pkg/deployer/container/pod.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#293 fix possible deadlock in ResolveBlueprintFromBlobResolver
  pkg/landscaper/blueprints/resolve.go
  pkg/landscaper/blueprints/resolve_test.go
  pkg/utils/context_aware_writer.go
Labels: kind/bug, kind/test, needs/ok-to-test, needs/changes, needs/review, size/m, priority/3, area/operations

#301 test documentation
  docs/README.md
  docs/development/testing.md
  docs/images/TestMachineryITSetup.png
  hack/testcluster/README.md
Labels: area/documentation, kind/task, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#305 fix defaulting for container deploy items
  pkg/deployer/container/container.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/container-deployer, priority/3

#308 make name and namespace in helm deployer providerconfig mandatory
  apis/deployer/helm/v1alpha1/validation/validation.go
  pkg/deployer/helm/helm_suite_test.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/validation/validation.go
Labels: kind/enhancement, kind/test, needs/ok-to-test, needs/review, size/xs, area/helm-deployer, priority/3

#306 added new landscaper controller option "--landscaper-kubeconfig"
  charts/landscaper/templates/cluster-kubeconfig-secret.yaml
  charts/landscaper/templates/deployment-controller.yaml
  charts/landscaper/templates/deployment-webhooks.yaml
  charts/landscaper/templates/rbac-agent.yaml
  charts/landscaper/templates/rbac-controller.yaml
  charts/landscaper/templates/rbac-webhooks.yaml
  charts/landscaper/templates/rolebinding.yaml
  charts/landscaper/templates/serviceaccount.yaml
  charts/landscaper/values.yaml
  cmd/landscaper-controller/app/app.go
  cmd/landscaper-controller/app/options.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#311 add unrecoverable reconcile test
  apis/deployer/container/v1alpha1/validation/validation.go
  apis/errors/error.go
  apis/errors/error_test.go
  pkg/deployer/container/container_suite_test.go
  test/utils/envtest/environment.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/validation/validation.go
  vendor/github.com/gardener/landscaper/apis/errors/error.go
Labels: kind/test, needs/ok-to-test, reviewed/lgtm, size/m, area/deployers, priority/3

#315 Add email notifications for failed head-update jobs
  .ci/pipeline_definitions
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, needs/review, size/xs, priority/3

#314 Improve integration tests
  test/integration/deployers/management/dm_tests.go
  test/integration/installations/phase-propagation.go
Labels: kind/technical-debt, needs/ok-to-test, needs/review, size/xs, area/testing, priority/3

#316 Update pipeline_definitions
  .ci/pipeline_definitions
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, needs/review, size/xs, priority/3

#319 remove undefined exports from exportExecution result
  pkg/landscaper/installations/exports/constructor.go
Labels: kind/bug, kind/test, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#317 fix landscaper deletion lifecycle
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/controllers/installations/reconcile_delete_test.go
  pkg/landscaper/controllers/installations/testdata/registry/blobs/root-no-imports/blueprint.yaml
  pkg/landscaper/controllers/installations/testdata/registry/component-descriptor.yaml
  pkg/landscaper/controllers/installations/testdata/state/test3/00-root.yaml
  pkg/landscaper/controllers/installations/testdata/state/test3/10-exec.yaml
  pkg/landscaper/installations/context.go
  pkg/landscaper/installations/context_test.go
  pkg/landscaper/installations/executions/complete.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/imports/helper.go
  pkg/landscaper/installations/imports/validation.go
  pkg/landscaper/installations/installation.go
  pkg/landscaper/installations/installations_suite_test.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/subinstallations/helper.go
  pkg/utils/simplelogger/logger.go
  test/framework/dump.go
  test/landscaper/e2e/inlinecd_test.go
  test/landscaper/e2e/simple_test.go
  test/utils/controller.go
  test/utils/envtest/fake_client.go
  test/utils/envtest/state.go
Labels: kind/test, kind/cleanup, needs/ok-to-test, needs/review, needs/second-opinion, size/xl, priority/3, area/operations

#323 update golang to 1.17
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#321 Add k8s resources creation and updating order
  apis/.schemes/helm-v1alpha1-ProviderStatus.json
  apis/.schemes/manifest-v1alpha2-ProviderStatus.json
  apis/deployer/manifest/types_provider.go
  apis/deployer/manifest/v1alpha1/conversions.go
  apis/deployer/manifest/v1alpha1/conversions_test.go
  apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
  apis/deployer/manifest/zz_generated.deepcopy.go
  apis/deployer/utils/managedresource/types.go
  apis/openapi/openapi_generated.go
  pkg/api/types.go
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/helm.go
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/lib/resourcemanager/exporter.go
  pkg/deployer/lib/resourcemanager/exporter_test.go
  pkg/deployer/lib/resourcemanager/objectapplier.go
  pkg/deployer/lib/resourcemanager/objectapplier_test.go
  pkg/deployer/lib/resourcemanager/resourcemanager_suite_test.go
  pkg/deployer/manifest/ensure.go
  pkg/deployer/manifest/manifest.go
  pkg/deployer/manifest/manifest_suite_test.go
  pkg/landscaper/registry/components/mock/resolver_mock.go
  pkg/utils/kubernetes/kubernetes.go
  pkg/utils/kubernetes/mock/client_mock.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/types_provider.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/conversions.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/deployer/utils/managedresource/types.go
Labels: kind/bug, kind/api-change, kind/test, needs/ok-to-test, reviewed/lgtm, size/xl, area/helm-deployer, area/manifest-deployer, priority/3

#326 fix bug which prevents 'empty' installations from getting a phase
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/installations/helper.go
Labels: area/robustness, kind/bug, needs/ok-to-test, needs/review, size/xs, priority/3

#324 simplfied the usage of the teststate helper struct
  cmd/landscaper-controller/app/app_test.go
  pkg/deployer/container/container_suite_test.go
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/lib/readinesscheck/readiness_suite_test.go
  pkg/deployer/lib/resourcemanager/exporter_test.go
  pkg/deployer/lib/resourcemanager/objectapplier_test.go
  pkg/deployer/lib/targetselector/e2e_suite_test.go
  pkg/deployer/manifest/manifest_suite_test.go
  pkg/deployer/manifest/test/e2e_test.go
  pkg/deployermanagement/controller/controller_reconcile_test.go
  pkg/deployermanagement/controller/deployer_management_test.go
  pkg/landscaper/controllers/componentoverwrites/componentoverwrites_controller_suite_test.go
  pkg/landscaper/controllers/execution/reconcile_test.go
  pkg/landscaper/controllers/installations/reconcile_delete_test.go
  test/framework/framework.go
  test/integration/core/registry.go
  test/integration/deployers/blueprints/blueprints_tests.go
  test/integration/deployers/container_tests.go
  test/integration/deployers/helmcharts/chartstests.go
  test/integration/deployers/management/dm_tests.go
  test/integration/deployers/manifest_tests.go
  test/integration/deployitems/timeouts.go
  test/integration/installations/import-export.go
  test/integration/installations/phase-propagation.go
  test/integration/tutorial/aggregated-blueprint.go
  test/integration/tutorial/external-jsonschema.go
  test/integration/tutorial/ingress-nginx.go
  test/integration/tutorial/simple-import.go
  test/integration/webhook/webhook.go
  test/utils/envtest/environment.go
  test/utils/envtest/fake_client.go
  test/utils/envtest/state.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/l, priority/3

#292 add reconcile extension concept to deployer lib
  docs/README.md
  docs/development/dep-lib-extension-hooks.md
  pkg/deployer/container/reconciler_deployitem.go
  pkg/deployer/helm/deployer.go
  pkg/deployer/lib/controller.go
  pkg/deployer/lib/extension/hook.go
  pkg/deployer/lib/extension/result.go
  pkg/deployer/lib/utils.go
  pkg/deployer/manifest/controller.go
  pkg/deployer/mock/controller.go
Labels: kind/enhancement, kind/test, needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/xl, area/deployers, priority/3

#330 add example for the preserveDir option
  docs/tutorials/02-local-simple-blueprint.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/changes, needs/review, size/xs, priority/4

#333 pin ingress-nginx chart version to v3.29.0
  docs/tutorials/01-create-simple-blueprint.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#332 replace the local setup tutorial with a landscaper-cli quickstart tutorial
  docs/README.md
  docs/tutorials/00-landscaper-installation.md
  docs/tutorials/00-local-setup.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/l, priority/4

#325 Add api-definitions for the context
  apis/core/types_context.go
  apis/core/types_dataobject.go
  apis/core/types_installation.go
  apis/core/v1alpha1/defaults.go
  apis/core/v1alpha1/defaults_test.go
  apis/core/v1alpha1/register.go
  apis/core/v1alpha1/types_context.go
  apis/core/v1alpha1/types_dataobject.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/types_shared_test.go
  apis/core/v1alpha1/types_suite_test.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  docs/api-reference/core.md
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_contexts.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_dataobjects.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  vendor/github.com/gardener/landscaper/apis/core/types_context.go
  vendor/github.com/gardener/landscaper/apis/core/types_dataobject.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/doc.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/register.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_context.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_dataobject.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: kind/api-change, needs/ok-to-test, reviewed/lgtm, size/xl, priority/3
