Repository gardener/landscaper, pull requests merged in 2021-12, with the labels that each got.

#386 Reuse secret in service accounts
  charts/container-deployer/templates/_helpers.tpl
  charts/helm-deployer/templates/_helpers.tpl
  charts/manifest-deployer/templates/_helpers.tpl
  controller-utils/pkg/kubernetes/kubernetes.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/kubernetes/kubernetes.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/deployers, priority/3

#387 add namespace read permissions as needed by the context controller
  charts/landscaper/charts/rbac/templates/clusterrole-controller.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3, area/operations

#389 Make helm deployer deploy CRDs
  go.mod
  pkg/deployer/helm/deployer.go
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/helm.go
  pkg/deployer/helm/helm_suite_test.go
  pkg/deployer/helm/testdata/testchart/crds/crontabs.yaml
  pkg/deployer/lib/resourcemanager/objectapplier.go
  vendor/modules.txt
Labels: kind/bug, kind/test, needs/ok-to-test, reviewed/lgtm, size/m, area/helm-deployer, priority/3
