Repository gardener/landscaper, pull requests merged in 2021-01, with the labels that each got.

#88 fixes wrong property name in helm chart
  charts/landscaper/templates/_helpers.tpl
Labels: needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#86 fix minor inconsistencies and typos in documentation
  README.md
  docs/concepts/Glossary.md
  docs/deployer/README.md
  docs/gettingstarted/install-landscaper-controller.md
  docs/old/Blueprints.md
  docs/usage/Blueprints.md
  docs/usage/Installations.md
  docs/usage/TemplateExecutors.md
  examples/10-Example-Blueprint.yaml
  pkg/apis/core/validation/blueprint.go
Labels: area/quality, kind/api-change, kind/cleanup, needs/ok-to-test, priority/normal, reviewed/lgtm, size/m

#84 Add namespace creation to install-landscaper-controller.md
  docs/gettingstarted/install-landscaper-controller.md
Labels: area/documentation, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#83 [Fix]- Helm deployer is failing with nil reference which crash the whole landscaper
  pkg/deployer/helm/ensure.go
Labels: kind/bug, needs/changes, needs/ok-to-test, priority/normal, size/xs

#79 add blueprint definition to templating import values
  docs/usage/Blueprints.md
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/executions/template/template.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/installations/executions/template/testdata/gotemplate/template-11.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/template-11.yaml
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, size/m

#89 Remove dependency breaking build under Mac
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/OpenAPIv2/README.md
  vendor/github.com/googleapis/gnostic/OpenAPIv2/openapi-2.0.json
Labels: area/os, kind/bug, needs/changes, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#82 add additional chart pull options
  docs/api-reference/core.md
  docs/deployer/helm.md
  pkg/apis/.schemas/helm_ProviderConfiguration.json
  pkg/apis/core/types_deployitem.go
  pkg/apis/core/types_execution.go
  pkg/apis/core/v1alpha1/types_deployitem.go
  pkg/apis/core/v1alpha1/types_execution.go
  pkg/apis/core/v1alpha1/types_target.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/deployer/helm/types_provider.go
  pkg/apis/deployer/helm/v1alpha1/helper/helper.go
  pkg/apis/deployer/helm/v1alpha1/types_provider.go
  pkg/apis/deployer/helm/v1alpha1/validation/validation.go
  pkg/apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  pkg/apis/deployer/helm/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/deployer/helm/zz_generated.deepcopy.go
  pkg/apis/deployer/manifest/v1alpha1/validation/validation.go
  pkg/apis/deployer/manifest/v1alpha2/validation/validation.go
  pkg/apis/deployer/mock/v1alpha1/validation/validation.go
  pkg/deployer/container/container.go
  pkg/deployer/container/init/init.go
  pkg/deployer/helm/actuator.go
  pkg/deployer/helm/chartresolver/chart.go
  pkg/deployer/helm/chartresolver/chartresolver_suite_test.go
  pkg/deployer/helm/chartresolver/constants.go
  pkg/deployer/helm/chartresolver/helmresolver.go
  pkg/deployer/helm/chartresolver/testdata/testchart/.helmignore
  pkg/deployer/helm/chartresolver/testdata/testchart/Chart.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart/values.yaml
  pkg/deployer/helm/helm.go
  pkg/deployer/helm/registry/client.go
  pkg/deployer/helm/test/e2e_test.go
  pkg/deployer/helm/test/helmdeployer_suite_test.go
  pkg/deployer/manifest/manifest.go
  pkg/deployer/mock/configuration.go
  pkg/landscaper/controllers/installations/registry.go
  pkg/landscaper/execution/reconcile_test.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/registry/components/oci.go
  pkg/landscaper/registry/components/oci_test.go
  pkg/utils/kubernetes/kubernetes.go
  test/landscaper/e2e/simple_test.go
  test/utils/envtest/environment.go
  test/utils/envtest/state.go
  test/utils/envtest/types.go
  test/utils/utils.go
Labels: area/usability, kind/api-change, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, priority/normal, size/xl

#94 Fix manifest decoder scheme
  pkg/deployer/manifest/ensure.go
  pkg/deployer/manifest/manifest.go
Labels: kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
