Repository gardener/landscaper, pull requests merged in 2022-05, with the labels that each got.

#478 refactor execution reconcile
  docs/technical/execution_controller.md
  pkg/landscaper/execution/generations.go
  pkg/landscaper/execution/reconcile.go
Labels: area/quality, kind/cleanup, needs/ok-to-test, needs/review, needs/second-opinion, size/xl, priority/3

#474 update virtual-garden to v0.5.0
  .landscaper/landscaper-service/blueprint/installation/landscaper-rbac-subinst.yaml
  .landscaper/landscaper-service/blueprint/installation/virtual-garden-subinst.yaml
  .landscaper/landscaper-service/component-references.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3, area/operations

#479 Improve context docu
  docs/usage/Context.md
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, area/deployers, priority/3

#481 mitigation for CVE-2022-28391
  Dockerfile
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, priority/2

#482 Guewa
  .test-defs/install-landscaper.yaml
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs, priority/3

#480 Fix excessive logging of the installation controller
  apis/errors/error.go
  pkg/landscaper/controllers/context/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/installations/context.go
  pkg/landscaper/installations/context_test.go
  pkg/landscaper/installations/operation.go
  pkg/utils/read_write_layer/consts.go
  pkg/utils/read_write_layer/logger.go
  pkg/utils/read_write_layer/write.go
  vendor/github.com/gardener/landscaper/apis/errors/error.go
Labels: area/robustness, kind/bug, needs/ok-to-test, needs/review, size/m, priority/3

#483 Simplify reconcile helper
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/installations/reconcilehelper/outdated_test.go
  pkg/landscaper/installations/reconcilehelper/reconcilehelper.go
  pkg/landscaper/installations/reconcilehelper/validation_test.go
  pkg/utils/requirements.go
  pkg/utils/requirements_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/l, area/deployers, priority/3

#485 fix missing rebasing
  pkg/landscaper/installations/executions/executions_test.go
  pkg/landscaper/installations/imports/importexec_test.go
Labels: area/quality, kind/technical-debt, needs/ok-to-test, needs/review, size/xs, priority/1

#484 Reconcile diagrams
  docs/technical/images/inst-force-reconcile.png
  docs/technical/images/inst-main-reconcile.png
  docs/technical/images/inst-recheck-completed.png
  docs/technical/images/inst-standard-reconcile.png
  docs/technical/installation_controller.md
Labels: area/documentation, kind/task, needs/ok-to-test, needs/changes, needs/review, size/s, priority/3

#486 Full reconcile
  apis/core/types_execution.go
  apis/core/types_shared.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  docs/api-reference/core.md
  docs/technical/installation_controller.md
  docs/technical/reconciliation_flow.md
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_test.go
  pkg/landscaper/controllers/installations/testdata/registry/blobs/root3/blueprint.yaml
  pkg/landscaper/controllers/installations/testdata/registry/component-descriptor.yaml
  pkg/landscaper/controllers/installations/testdata/state/test5/00-root.yaml
  pkg/landscaper/controllers/installations/testdata/state/test5/10-exec.yaml
  pkg/landscaper/controllers/installations/testdata/state/test5/10-subinst.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/reconcilehelper/reconcilehelper.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  pkg/utils/read_write_layer/consts.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
Labels: area/robustness, kind/bug, needs/ok-to-test, reviewed/lgtm, size/l, priority/3

#488 Handle prefix of docker image reference
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/executions/template/helper.go
  pkg/utils/read_write_layer/logger.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/s, area/oci, priority/3

#490 retrigger failed deployer
  pkg/deployermanagement/config/deployment.go
  pkg/deployermanagement/controller/deployer_management_reconcile.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3
