Repository gardener/landscaper, pull requests merged in 2023-12, with the labels that each got.

#915 Log read ops
  controller-utils/pkg/logging/constants/constants.go
  pkg/agent/agent.go
  pkg/deployer/container/container_reconcile.go
  pkg/deployer/container/garbage_collector.go
  pkg/deployer/container/pod.go
  pkg/deployer/container/state/state.go
  pkg/deployer/container/wait/uploadexport.go
  pkg/deployer/container/wait/wait.go
  pkg/deployer/lib/controller.go
  pkg/deployer/lib/interruption_checker.go
  pkg/deployer/lib/readinesscheck/customreadinesscheck.go
  pkg/deployer/lib/readinesscheck/readiness.go
  pkg/deployer/lib/resourcemanager/exporter.go
  pkg/deployer/lib/resourcemanager/objectapplier.go
  pkg/deployer/lib/utils.go
  pkg/deployer/manifest/ensure.go
  pkg/deployermanagement/controller/controller.go
  pkg/deployermanagement/controller/deployer_management_delete.go
  pkg/deployermanagement/controller/deployer_management_reconcile.go
  pkg/landscaper/controllers/deployitem/reconcile.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/healthcheck/healthchecker.go
  pkg/landscaper/controllers/installations/cleaner.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/targetsync/targetsync_controller.go
  pkg/landscaper/execution/execution.go
  pkg/landscaper/execution/helper.go
  pkg/landscaper/installations/context.go
  pkg/landscaper/installations/executions/complete.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/exports/constructor.go
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/trigger.go
  pkg/utils/clusters/source_client_provider.go
  pkg/utils/landscaper/landscaper.go
  pkg/utils/lock/lock_cleaner.go
  pkg/utils/lock/locker.go
  pkg/utils/read_write_layer/consts.go
  pkg/utils/read_write_layer/read.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/logging/constants/constants.go
Labels: kind/enhancement, needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/l, area/deployers, priority/3

#920 Improve PR template
  .github/pull_request_template.md
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#929 Fix docu
  docs/guided-tour/hello-world/README.md
  docs/usage/Installations.md
Labels: needs/ok-to-test, needs/review, size/xs

#927 Remove dependency to the image-vector repository
  go.mod
  go.sum
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/landscaper/installations/executions/template/spiff/funcs.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/installations/executions/template/testdata/gotemplate/template-12.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/component-descriptor-12.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/result-12.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/text/template-12.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/yaml/template-12.yaml
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/cdutils/resources.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/cdutils/utils.go
  vendor/github.com/gardener/image-vector/pkg/docs.go
  vendor/github.com/gardener/image-vector/pkg/imagevector.go
  vendor/github.com/gardener/image-vector/pkg/overwrite.go
  vendor/github.com/gardener/image-vector/pkg/types.go
  vendor/github.com/gardener/image-vector/pkg/utils.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#924 Pod cache for controller synchronisation
  pkg/deployer/lib/controller.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/utils/lock/locker.go
  pkg/utils/lock/podcache/pod_cache.go
  pkg/utils/lock/podcache/pod_cache_suite_test.go
  pkg/utils/lock/podcache/pod_cache_test.go
  pkg/utils/metadata.go
  pkg/utils/read_write_layer/consts.go
  pkg/utils/read_write_layer/read.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l
