Repository gardener/landscaper, pull requests merged in 2023-02, with the labels that each got.

#679 New cd construction
  .ci/component_descriptor
Labels: area/delivery, kind/cleanup, needs/ok-to-test, needs/review, size/xs, priority/3

#682 fix pipeline
  .ci/integration-test-new
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, reviewed/lgtm, size/xs, priority/1

#681 make build work on arm / prepare multiarch build
  .ci/component_descriptor
  Makefile
  hack/prepare-docker-builder.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s, priority/3

#689 Token Template Function
  pkg/deployer/lib/controller.go
  pkg/deployer/manifest/export_test.go
  pkg/deployer/manifest/misc_test.go
  pkg/deployer/manifest/policy_test.go
  pkg/deployer/manifest/readiness_check_test.go
  pkg/landscaper/controllers/targetsync/constants.go
  pkg/landscaper/controllers/targetsync/source_client_provider.go
  pkg/landscaper/controllers/targetsync/targetsync_controller.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/landscaper/installations/executions/template/gotemplate/gotemplate.go
  pkg/landscaper/installations/executions/template/gotemplate/gotemplate_test.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/installations/exports/constructor.go
  pkg/landscaper/installations/imports/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  pkg/utils/landscaper/blueprint.go
  pkg/utils/targetresolver/secret/secretrefresolver.go
  pkg/utils/targetresolver/targetresolver.go
  pkg/utils/token/shoot_client.go
  pkg/utils/token/token_client.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl, priority/3

#693 Templating Function for Service Account Kubeconfig
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/utils/token/token_client.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#694 Improve import/export docu
  docs/guided-tour/import-export/export-parameters/README.md
  docs/usage/Installations.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, needs/review, size/xs, priority/3

#695 Docu for Kubeconfig Templating Functions
  docs/usage/Templating.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, priority/3

#696 Templating Function to Build OIDC Kubeconfigs
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/utils/token/oidc_kubeconfig_builder.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#697 Remove todo from guided tour list
  docs/guided-tour/README.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, needs/review, size/xs, priority/3
