Repository gardener/landscaper, pull requests merged in 2023-01, with the labels that each got.

#665 Check Interruption of Readiness Check and Export Collection
  pkg/deployer/helm/ensure.go
  pkg/deployer/lib/interruption_checker.go
  pkg/deployer/lib/readinesscheck/customreadinesscheck.go
  pkg/deployer/lib/readinesscheck/defaultreadinesscheck.go
  pkg/deployer/lib/readinesscheck/readiness.go
  pkg/deployer/lib/resourcemanager/exporter.go
  pkg/deployer/manifest/ensure.go
Labels: area/robustness, kind/bug, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#668 Wait Intervals during Export Collection
  pkg/deployer/lib/resourcemanager/exporter.go
Labels: area/quality, kind/bug, needs/ok-to-test, needs/review, size/xs, priority/3

#666 Guided Tour: Example for Export Parameters
  docs/guided-tour/README.md
  docs/guided-tour/import-export/export-parameters/README.md
  docs/guided-tour/import-export/export-parameters/blueprint/blueprint.yaml
  docs/guided-tour/import-export/export-parameters/commands/push-blueprint.sh
  docs/guided-tour/import-export/export-parameters/commands/push-component-descriptor.sh
  docs/guided-tour/import-export/export-parameters/component-descriptor.yaml
  docs/guided-tour/import-export/export-parameters/installation/context.yaml
  docs/guided-tour/import-export/export-parameters/installation/installation.yaml
  docs/guided-tour/import-export/export-parameters/installation/target.yaml
  docs/guided-tour/import-export/export-parameters/linkages.png
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/second-opinion, size/l, priority/3

#670 add dns settings to landscaper webhook ingress
  .landscaper/landscaper-service/blueprint/landscaper/deploy-execution.yaml
  charts/landscaper/charts/landscaper/templates/ingress.yaml
  charts/landscaper/charts/landscaper/values.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, priority/3, area/operations

#672 correct some issues in the documentation
  docs/technical/deployer_lifecycle_management.md
Labels: area/documentation, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, priority/4

#674 Improve int tests
  test/integration/executions/generations.go
  test/integration/targets/targets.go
  test/integration/tutorial/ingress-nginx.go
  test/integration/webhook/webhook.go
Labels: kind/test, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#675 add audit configuration to landscaper-service component
  .landscaper/landscaper-service/blueprint/installation/blueprint.yaml
  .landscaper/landscaper-service/blueprint/installation/shoot-cluster-subinst.yaml
  .landscaper/landscaper-service/blueprint/shoot/blueprint.yaml
  .landscaper/landscaper-service/blueprint/shoot/deploy-execution.yaml
  test/landscaper/landscaper_service_blueprints/landscaper_service_blueprint_test.go
  test/landscaper/landscaper_service_blueprints/testdata/auditpolicy.yaml
  test/landscaper/landscaper_service_blueprints/testdata/imports-installation.yaml
  test/landscaper/landscaper_service_blueprints/testdata/imports-shoot.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#676 Add missing refs to component descriptor
  .ci/component_descriptor
  .landscaper/component-references.yaml
  .landscaper/resources.yaml
Labels: area/delivery, kind/enhancement, needs/ok-to-test, needs/review, size/s, priority/3

#678 Cleanup landscaper-service Component
  .ci/component_descriptor
  .landscaper/landscaper-service/blueprint/installation/blueprint.yaml
  .landscaper/landscaper-service/blueprint/installation/landscaper-deployment-subinst.yaml
  .landscaper/landscaper-service/blueprint/installation/landscaper-rbac-subinst.yaml
  .landscaper/landscaper-service/blueprint/installation/shoot-cluster-subinst.yaml
  .landscaper/landscaper-service/blueprint/landscaper/blueprint.yaml
  .landscaper/landscaper-service/blueprint/landscaper/deploy-execution.yaml
  .landscaper/landscaper-service/blueprint/rbac/blueprint.yaml
  .landscaper/landscaper-service/blueprint/rbac/deploy-execution.yaml
  .landscaper/landscaper-service/blueprint/rbac/export-execution.yaml
  .landscaper/landscaper-service/blueprint/shoot/blueprint.yaml
  .landscaper/landscaper-service/blueprint/shoot/deploy-execution.yaml
  .landscaper/landscaper-service/blueprint/shoot/export-execution.yaml
  .landscaper/landscaper-service/component-references.yaml
  .landscaper/landscaper-service/definition/landscaper-configuration.json
  .landscaper/landscaper-service/definition/registry-configuration.json
  .landscaper/landscaper-service/definition/shoot-configuration.json
  .landscaper/landscaper-service/resources.yaml
  docs/README.md
  docs/gettingstarted/install-landscaper-service.md
  test/landscaper/landscaper_service_blueprints/landscaper_service_blueprint_test.go
  test/landscaper/landscaper_service_blueprints/testdata/auditpolicy.yaml
  test/landscaper/landscaper_service_blueprints/testdata/imports-installation.yaml
  test/landscaper/landscaper_service_blueprints/testdata/imports-landscaper.yaml
  test/landscaper/landscaper_service_blueprints/testdata/imports-rbac.yaml
  test/landscaper/landscaper_service_blueprints/testdata/imports-shoot.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/landscaper-blueprint/blueprint.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/landscaper-blueprint/deploy-execution.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/landscaper-configuration/schema.json
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/rbac-blueprint/blueprint.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/rbac-blueprint/deploy-execution.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/rbac-blueprint/export-execution.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/registry-configuration/schema.json
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/shoot-blueprint/blueprint.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/shoot-blueprint/deploy-execution.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/shoot-blueprint/export-execution.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/blobs/shoot-configuration/schema.json
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper-service/component-descriptor.yaml
  test/landscaper/landscaper_service_blueprints/testdata/registry/landscaper/component-descriptor.yaml
Labels: area/robustness, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xl, priority/3

#677 use minimalistic helm chart instead of nginx chart for helm deployer test
  test/integration/deployers/blueprints/blueprints_tests.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing, priority/3
