Repository gardener/landscaper, pull requests merged in 2023-11, with the labels that each got.

#868 Add main landscaper deployment to health checklist
  apis/.schemes/config-v1alpha1-LandscaperConfiguration.json
  apis/config/types_landscaper_config.go
  apis/config/v1alpha1/types_landscaper_config.go
  apis/config/v1alpha1/zz_generated.conversion.go
  apis/openapi/openapi_generated.go
  apis/vendor/k8s.io/code-generator/CONTRIBUTING.md
  apis/vendor/k8s.io/code-generator/LICENSE
  apis/vendor/k8s.io/code-generator/OWNERS
  apis/vendor/k8s.io/code-generator/README.md
  apis/vendor/k8s.io/code-generator/SECURITY_CONTACTS
  apis/vendor/k8s.io/code-generator/code-of-conduct.md
  apis/vendor/k8s.io/code-generator/doc.go
  apis/vendor/k8s.io/code-generator/generate-groups.sh
  apis/vendor/k8s.io/code-generator/generate-internal-groups.sh
  apis/vendor/k8s.io/code-generator/tools.go
  charts/landscaper/charts/landscaper/templates/_helpers.tpl
  controller-utils/go.mod
  controller-utils/go.sum
  controller-utils/vendor/github.com/gardener/landscaper/apis/config/types_landscaper_config.go
  controller-utils/vendor/golang.org/x/oauth2/README.md
  controller-utils/vendor/golang.org/x/oauth2/oauth2.go
  controller-utils/vendor/golang.org/x/oauth2/token.go
  controller-utils/vendor/modules.txt
  pkg/landscaper/controllers/healthcheck/controller.go
  pkg/landscaper/controllers/healthcheck/reconcile_test.go
  pkg/landscaper/controllers/healthcheck/testdata/test1/deployments.yaml
  pkg/landscaper/controllers/healthcheck/testdata/test2/deployments.yaml
  vendor/github.com/gardener/landscaper/apis/config/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/zz_generated.conversion.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/m, priority/3, area/operations

#870 Timeout reason during cleanup orphaned resources
  pkg/deployer/lib/resourcemanager/objectapplier.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/s, area/deployers, priority/3

#863 Templating with v3alpha1
  docs/guided-tour/templating/components/README.md
  docs/usage/Templating.md
  pkg/components/cnudie/componentversion.go
  pkg/components/model/componentversion.go
  pkg/components/ocmlib/componentversion.go
  pkg/components/testutils/componentversion.go
  pkg/landscaper/installations/executions/template/common/utils.go
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/landscaper/installations/executions/template/gotemplate/gotemplate.go
  pkg/landscaper/installations/executions/template/helper.go
  pkg/landscaper/installations/executions/template/options.go
  pkg/landscaper/installations/executions/template/spiff/funcs.go
  pkg/landscaper/installations/executions/template/spiff/spifftemplate.go
  pkg/landscaper/installations/executions/template/template.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/installations/executions/template/testdata/gotemplate/template-04.yaml
  pkg/landscaper/installations/executions/template/testdata/gotemplate/template-30.yaml
  pkg/landscaper/installations/executions/template/testdata/gotemplate/template-31.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v2-mixed.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v2-ref1.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v2-ref2.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v2.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v3-mixed.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v3-ref1.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v3-ref2.yaml
  pkg/landscaper/installations/executions/template/testdata/shared_data/localocmrepository/component-descriptor-v3.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/text/template-30.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/text/template-31.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/yaml/template-30.yaml
  pkg/landscaper/installations/executions/template/testdata/spifftemplate/yaml/template-31.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/xl, priority/1

#877 Fix for missing context of deploy items
  pkg/deployer/lib/controller.go
  test/integration/core/registry.go
  test/integration/dependencies/dependencies.go
  test/integration/deployers/blueprints/blueprints_tests.go
  test/integration/deployers/container/containertests.go
  test/integration/deployers/helmcharts/chartstests.go
  test/integration/deployers/helmdeployer/helm_deployer_tests.go
  test/integration/deployers/management/dm_tests.go
  test/integration/deployers/manifest_tests.go
  test/integration/deployitems/timeouts.go
  test/integration/executions/generations.go
  test/integration/importexport/import_data_mappings.go
  test/integration/importexport/import_executions.go
  test/integration/importexport/import_export.go
  test/integration/importexport/import_validation.go
  test/integration/inline/context.go
  test/integration/inline/inline_blueprints.go
  test/integration/inline/inline_templates.go
  test/integration/installations/import-export.go
  test/integration/rootinstallations/rootinstallations.go
  test/integration/subinstallations/subinstallations.go
  test/integration/targets/targets.go
  test/integration/tutorial/aggregated-blueprint.go
  test/integration/tutorial/external-jsonschema.go
  test/integration/tutorial/ingress-nginx.go
  test/integration/tutorial/simple-import.go
  test/integration/webhook/webhook.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/m, area/deployers, priority/3

#879 Fix int tests
  test/integration/deployers/blueprints/blueprints_tests.go
  test/utils/envtest/state.go
Labels: kind/test, needs/ok-to-test, needs/review, size/s, area/deployers, priority/3

#882 Log errors during di reconciliation
  pkg/deployer/lib/controller.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#884 ingress-chart readme fix
  docs/tutorials/resources/local-ingress-nginx/chart/ingress-nginx/README.md
Labels: needs/ok-to-test, needs/review, size/xs

#886 deleting <br>s from 02-local-simple-blueprint.md
  docs/tutorials/02-local-simple-blueprint.md
Labels: needs/ok-to-test, needs/review, size/xs

#887 Delete <br>s from 03-simple-import.md
  docs/tutorials/03-simple-import.md
Labels: needs/ok-to-test, needs/review, size/xs

#888 Delete <br> 04-aggregated-blueprint.md
  docs/tutorials/04-aggregated-blueprint.md
Labels: needs/ok-to-test, needs/review, size/xs

#891 Fix LandscaperCli.md for docu generation
  docs/usage/LandscaperCli.md
Labels: needs/ok-to-test, needs/review, size/xs

#890 Fix Installations.md for docu gen
  docs/usage/Installations.md
Labels: needs/ok-to-test, needs/review, size/xs

#889 Fix Blueprints.md for docu generation
  docs/usage/Blueprints.md
Labels: needs/ok-to-test, needs/review, size/s

#885 fix credential propagation for oci helm resource
  pkg/components/cnudie/factory.go
  pkg/components/model/factory.go
  pkg/components/ocmlib/factory.go
  pkg/components/ocmlib/ocm_test.go
  pkg/components/ocmlib/registryaccess.go
  pkg/components/ocmlib/suite_test.go
  pkg/deployer/helm/chartresolver/chart.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/m, area/deployers, priority/1

#869 Missing target
  pkg/landscaper/controllers/deployitem/reconcile.go
  pkg/landscaper/controllers/deployitem/reconcile_test.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, needs/review, size/s, priority/3

#893 create new ocm context per reconciliation
  pkg/components/ocmlib/factory.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/1

#892 Integration test: use target selectors in blueprints test
  hack/int-test-helper/install-landscaper
  test/integration/deployers/blueprints/blueprints_tests.go
Labels: kind/test, needs/ok-to-test, needs/review, size/s, area/testing, priority/3

#898 Fix synchronization
  cmd/landscaper-controller/app/app.go
  pkg/utils/lock/lock_cleaner.go
  pkg/utils/read_write_layer/logger.go
  pkg/utils/read_write_layer/write.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#899 improve logs (run-int-tests)
  apis/core/types_shared.go
  apis/core/v1alpha1/types_shared.go
  controller-utils/pkg/webhook/webhook.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  pkg/deployer/helm/realhelmdeployer/real_helm_deployer.go
  pkg/deployer/lib/controller.go
  pkg/deployer/lib/utils.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/execution/reconcile_test.go
  pkg/landscaper/controllers/healthcheck/healthchecker.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/retry_helper.go
  pkg/landscaper/execution/execution.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  pkg/utils/loghelper.go
  test/landscaper/e2e/inlinecd_test.go
  test/landscaper/e2e/simple_test.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/webhook/webhook.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/m, area/deployers, priority/3

#903 Increase timeout of test deployitem
  test/integration/deployers/helmdeployer/helm_deployer_tests.go
Labels: kind/test, needs/ok-to-test, needs/review, size/xs, area/testing, priority/3

#902 Stabilize Integration Tests
  hack/testcluster/pkg/shootcluster_manager.go
Labels: needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/xs, priority/3

#910 enable debug log level for landscaper (especially webhooks)
  hack/int-test-helper/install-landscaper
  test/utils/kubernetes.go
Labels: needs/ok-to-test, needs/review, size/xs, priority/3

#911 document ocm feature switch for guided tour
  docs/guided-tour/README.md
  docs/guided-tour/blueprints/external-blueprint/README.md
  docs/installation/install-landscaper-controller.md
Labels: area/documentation, kind/technical-debt, needs/ok-to-test, needs/review, size/xs, priority/2
