Repository gardener/landscaper, pull requests merged in 2023-09, with the labels that each got.

#807 Reduce error logging
  pkg/deployer/lib/controller.go
  pkg/deployer/manifest/ensure.go
  pkg/landscaper/controllers/context/controller.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/controllers/installations/retry_helper.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/imports/constructor.go
  pkg/utils/constants.go
  pkg/utils/loghelper.go
Labels: kind/cleanup, needs/ok-to-test, needs/review, size/m, area/deployers, priority/3

#811 add HasAnnotation function to controller-utils library
  controller-utils/pkg/kubernetes/kubernetes.go
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, priority/3

#812 bump component-spec dependency
  go.mod
  go.sum
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/jsonschema/jsonschema_suite_test.go
  pkg/landscaper/registry/components/cdutils/uri_test.go
  test/integration/core/registry.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/componentdescriptor.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/jsonscheme/bindata.go
  vendor/github.com/gardener/component-spec/bindings-go/apis/v2/validation/validation.go
  vendor/github.com/gardener/component-spec/bindings-go/oci/constants.go
  vendor/github.com/gardener/component-spec/bindings-go/oci/manifest.go
  vendor/github.com/gardener/component-spec/bindings-go/oci/resolve.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/kubernetes/kubernetes.go
  vendor/modules.txt
Labels: area/quality, kind/technical-debt, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, priority/3

#819 Fix logging
  controller-utils/pkg/logging/logger.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/logging/logger.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#821 Metrics in Helm Chart Templates and Values
  charts/container-deployer/templates/hpa.yaml
  charts/container-deployer/values.yaml
  charts/helm-deployer/templates/hpa.yaml
  charts/helm-deployer/values.yaml
  charts/landscaper/charts/landscaper/templates/hpa-main-controller.yaml
  charts/landscaper/charts/landscaper/templates/hpa-webhook.yaml
  charts/landscaper/charts/landscaper/values.yaml
  charts/manifest-deployer/templates/hpa.yaml
  charts/manifest-deployer/values.yaml
  charts/mock-deployer/templates/hpa.yaml
  charts/mock-deployer/values.yaml
Labels: kind/task, needs/ok-to-test, reviewed/lgtm, size/m, area/scalability, priority/3

#822 Component Library Flag
  apis/core/types_deployitem.go
  apis/core/types_execution.go
  apis/core/types_installation.go
  apis/core/types_shared.go
  apis/core/v1alpha1/defaults.go
  apis/core/v1alpha1/types_deployitem.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  docs/api-reference/core.md
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_deployitems.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, area/oci, priority/3

#824 Revert "Component Library Flag"
  apis/core/types_deployitem.go
  apis/core/types_execution.go
  apis/core/types_installation.go
  apis/core/types_shared.go
  apis/core/v1alpha1/defaults.go
  apis/core/v1alpha1/types_deployitem.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  docs/api-reference/core.md
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_deployitems.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
Labels: needs/ok-to-test, needs/review, size/m

#826 Add feedback to deletion proposal
  docs/proposals/helm-manifest-deployer-ordering.md
Labels: kind/discussion, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#825 OCM Flag
  apis/.schemes/config-v1alpha1-LandscaperConfiguration.json
  apis/.schemes/container-v1alpha1-Configuration.json
  apis/.schemes/helm-v1alpha1-Configuration.json
  apis/.schemes/manifest-v1alpha1-Configuration.json
  apis/config/types_landscaper_config.go
  apis/config/v1alpha1/types_landscaper_config.go
  apis/config/v1alpha1/zz_generated.conversion.go
  apis/core/types_context.go
  apis/core/v1alpha1/types_context.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/deployer/container/types_config.go
  apis/deployer/container/v1alpha1/types_config.go
  apis/deployer/container/v1alpha1/zz_generated.conversion.go
  apis/deployer/helm/types_config.go
  apis/deployer/helm/v1alpha1/types_config.go
  apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  apis/deployer/manifest/types_config.go
  apis/deployer/manifest/v1alpha1/types_config.go
  apis/deployer/manifest/v1alpha1/zz_generated.conversion.go
  apis/deployer/manifest/v1alpha2/types_config.go
  apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
  apis/openapi/openapi_generated.go
  charts/container-deployer/templates/_helpers.tpl
  charts/container-deployer/values.yaml
  charts/helm-deployer/templates/_helpers.tpl
  charts/helm-deployer/values.yaml
  charts/landscaper/charts/landscaper/templates/_helpers.tpl
  charts/landscaper/charts/landscaper/values.yaml
  charts/manifest-deployer/templates/_helpers.tpl
  charts/manifest-deployer/values.yaml
  controller-utils/vendor/github.com/gardener/landscaper/apis/config/types_landscaper_config.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_context.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_context.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  docs/api-reference/core.md
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_contexts.yaml
  vendor/github.com/gardener/landscaper/apis/config/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/types_landscaper_config.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/types_context.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_context.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/container/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/helm/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/types_config.go
  vendor/github.com/gardener/landscaper/apis/deployer/manifest/v1alpha2/zz_generated.conversion.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, area/oci, priority/3

#823 Proposal timeouts and typical error page
  docs/guided-tour/README.md
  docs/guided-tour/error-handling/problem_analysis.md
  docs/proposals/timeouts.md
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/m, area/deployers, priority/3

#829 update pipeline definition
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, priority/3

#832 Fix blueprint docu
  docs/usage/Blueprints.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, needs/review, size/xs, priority/3

#835 Fix pipeline
  .ci/int-test
  .ci/int-test-helper/create-shoot-cluster
  .ci/int-test-helper/install-landscaper
  .ci/integration-test
  .ci/integration-test-new
  .ci/local-integration-test
  .ci/local-integration-test-with-cluster-creation
  hack/integration-test.py
  hack/testcluster/pkg/shootcluster_manager.go
  hack/testcluster/shootcluster_create.go
  hack/testcluster/shootcluster_delete.go
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, priority/1

#830 update pipeline definition for head updates
  .ci/pipeline_definitions
Labels: needs/review, reviewed/ok-to-test, size/xs, priority/3

#836 Pipeline fix
  .ci/integration-test
  .ci/pipeline_definitions
  .ci/update_release.py
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, priority/1

#839 Adjust script to pipeline conversion from true to True
  .ci/integration-test
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, priority/1
