Repository gardener/landscaper, pull requests merged in 2023-07, with the labels that each got.

#769 new manual component descriptor logic
  .ci/component_descriptor
  .ci/component_descriptor_real
  .landscaper/resources.yaml
  hack/create-dummy-cd.py
Labels: area/delivery, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m, priority/3

#778 Improve targetsync docu
  docs/usage/TargetSyncs.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, size/xs, priority/3

#775 Skip readiness check for disabled subcharts
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/helm_suite_test.go
  pkg/deployer/helm/realhelmdeployer/real_helm_deployer.go
  pkg/deployer/helm/testdata/testchart5/Chart.yaml
  pkg/deployer/helm/testdata/testchart5/charts/test-subchart/Chart.yaml
  pkg/deployer/helm/testdata/testchart5/charts/test-subchart/templates/configmap.yaml
  pkg/deployer/helm/testdata/testchart5/templates/configmap.yaml
  pkg/deployer/helm/testdata/testchart5/values.yaml
  pkg/deployer/lib/readinesscheck/defaultreadinesscheck.go
  pkg/deployer/lib/resourcemanager/exporter.go
  pkg/deployer/lib/resourcemanager/exporter_test.go
  pkg/deployer/manifest/ensure.go
Labels: kind/bug, needs/ok-to-test, needs/second-opinion, size/l, area/helm-deployer, priority/3

#782 update integration test image in pipeline to 1.20.6-alpine3.18
  .ci/pipeline_definitions
Labels: area/dev-productivity, kind/test, needs/ok-to-test, needs/review, size/xs, priority/1

#780 Log sync object name
  docs/README.md
  docs/technical/scaling.md
  pkg/utils/lock/locker.go
  test/integration/suite_test.go
Labels: area/logging, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, priority/3

#783 Improve timeout message
  pkg/landscaper/controllers/deployitem/reconcile.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#785 Remove pod permission
  pkg/deployermanagement/controller/deployer_management_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, priority/3

#787 Fix integration tests
  test/integration/deployers/container/containertests.go
  test/utils/envtest/fake_client.go
Labels: kind/test, needs/ok-to-test, needs/review, size/xs, area/testing, priority/3

#789 Permissions for deployers to list pods
  charts/helm-deployer/templates/clusterrole.yaml
  charts/manifest-deployer/templates/clusterrole.yaml
  charts/mock-deployer/templates/clusterrole.yaml
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, area/deployers, priority/3

#791 Disable client cache
  pkg/utils/read_write_layer/logger.go
  pkg/utils/uncached_client.go
Labels: area/robustness, kind/bug, needs/ok-to-test, needs/review, size/xs, priority/3

#795 Fix nilpointer during cleanup of orphaned subinstallations
  pkg/landscaper/controllers/installations/reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, priority/3
