Repository gardener/landscaper, pull requests merged in 2024-05, with the labels that each got.

#1104 Fix dpanic due to non-string logging key
  pkg/landscaper/controllers/installations/controller.go
Labels: needs/ok-to-test, needs/review, size/xs

#1095 Retry with cron schedule
  apis/core/types_installation.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/validation/installation.go
  apis/openapi/zz_generated.openapi.go
  docs/api-reference/core.md
  docs/usage/Installations.md
  pkg/landscaper/controllers/installations/retry_helper.go
  pkg/landscaper/controllers/installations/retry_helper_test.go
  pkg/landscaper/controllers/installations/testdata/state/test11/00-root.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
Labels: needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/l

#1090 refactor CRD embedding
  apis/crds/crds.go
  apis/crds/manifests/landscaper.gardener.cloud_componentversionoverwrites.yaml
  apis/crds/manifests/landscaper.gardener.cloud_contexts.yaml
  apis/crds/manifests/landscaper.gardener.cloud_criticalproblems.yaml
  apis/crds/manifests/landscaper.gardener.cloud_dataobjects.yaml
  apis/crds/manifests/landscaper.gardener.cloud_deployitems.yaml
  apis/crds/manifests/landscaper.gardener.cloud_executions.yaml
  apis/crds/manifests/landscaper.gardener.cloud_installations.yaml
  apis/crds/manifests/landscaper.gardener.cloud_lshealthchecks.yaml
  apis/crds/manifests/landscaper.gardener.cloud_syncobjects.yaml
  apis/crds/manifests/landscaper.gardener.cloud_targets.yaml
  apis/crds/manifests/landscaper.gardener.cloud_targetsyncs.yaml
  apis/go.mod
  apis/go.sum
  hack/generate-code.sh
  pkg/landscaper/crdmanager/crdmanager.go
  test/utils/envtest/environment.go
Labels: needs/ok-to-test, needs/changes, needs/review, size/s

#1105 Measure performance
  pkg/components/model/componentversion_refs.go
  pkg/components/ocmlib/factory.go
  pkg/components/ocmlib/registryaccess.go
  pkg/landscaper/blueprints/resolve.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/registry.go
  pkg/landscaper/installations/builder.go
  pkg/landscaper/installations/context.go
  pkg/landscaper/installations/executions/executions_test.go
  pkg/landscaper/installations/imports/importexec_test.go
  pkg/landscaper/installations/reconcilehelper/reconcilehelper.go
  pkg/landscaper/installations/reconcilehelper/validation_test.go
  pkg/utils/performance_measurement.go
  pkg/utils/verify/utils.go
Labels: needs/ok-to-test, needs/review, size/m

#1113 Update Hello World README.md
  docs/guided-tour/hello-world/README.md
Labels: needs/ok-to-test, needs/review, size/xs

#1117 Guided tour: export import example
  docs/guided-tour/README.md
  docs/guided-tour/subinstallations/export-import/README.md
  docs/guided-tour/subinstallations/export-import/blueprints/root/blueprint.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/root/export-execution.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/root/subinstallation-1.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/root/subinstallation-2.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/root/subinstallation-3.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/sub/blueprint.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/sub/deploy-execution.yaml
  docs/guided-tour/subinstallations/export-import/blueprints/sub/export-execution.yaml
  docs/guided-tour/subinstallations/export-import/commands/component-constructor.yaml
  docs/guided-tour/subinstallations/export-import/commands/component.sh
  docs/guided-tour/subinstallations/export-import/commands/delete-installation.sh
  docs/guided-tour/subinstallations/export-import/commands/delete-other-k8s-resources.sh
  docs/guided-tour/subinstallations/export-import/commands/deploy-k8s-resources.sh
  docs/guided-tour/subinstallations/export-import/commands/settings
  docs/guided-tour/subinstallations/export-import/images/export-import.excalidraw
  docs/guided-tour/subinstallations/export-import/images/export-import.png
  docs/guided-tour/subinstallations/export-import/installation/context.yaml.tpl
  docs/guided-tour/subinstallations/export-import/installation/dataobject.yaml.tpl
  docs/guided-tour/subinstallations/export-import/installation/installation.yaml.tpl
  docs/guided-tour/subinstallations/export-import/installation/target.yaml.tpl
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#1103 add landscaper aggregation cluster roles
  charts/landscaper/charts/rbac/templates/_helpers.tpl
  charts/landscaper/charts/rbac/templates/aggregation-clusterroles.yaml
  charts/landscaper/charts/rbac/values.yaml
Labels: needs/ok-to-test, needs/review, size/s

#1118 Guided tour: extend description of the export-import example
  docs/guided-tour/subinstallations/export-import/README.md
  docs/guided-tour/subinstallations/export-import/images/export-import.excalidraw
  docs/guided-tour/subinstallations/export-import/images/export-import.png
  docs/guided-tour/targets/README.md
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#1114 Caching of helm subcharts
  pkg/deployer/helm/chartresolver/chart_cache.go
  pkg/deployer/helm/chartresolver/chart_marshal.go
  pkg/deployer/helm/chartresolver/chart_marshal_test.go
  pkg/deployer/helm/chartresolver/testdata/testchart2/Chart.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/charts/test2-subchart/Chart.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/charts/test2-subchart/charts/test2-subsubchart/Chart.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/charts/test2-subchart/charts/test2-subsubchart/templates/configmap.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/charts/test2-subchart/charts/test2-subsubchart/values.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/charts/test2-subchart/templates/configmap.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/charts/test2-subchart/values.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/templates/configmap.yaml
  pkg/deployer/helm/chartresolver/testdata/testchart2/values.yaml
Labels: needs/ok-to-test, needs/review, size/m
