Repository gardener/landscaper, pull requests merged in 2024-03, with the labels that each got.

#996 cross-compile without emulation
  Dockerfile
  Makefile
  hack/install.sh
  hack/prepare-docker-builder.sh
Labels: needs/ok-to-test, needs/review, size/s

#995 frontmatter for target-maps and some link fixes
  docs/guided-tour/target-maps/01-multiple-deploy-items/README.md
  docs/guided-tour/target-maps/02-targetmap-ref/README.md
  docs/guided-tour/target-maps/03-multiple-subinst/README.md
  docs/guided-tour/target-maps/04-forward-map/README.md
  docs/guided-tour/target-maps/05-other-examples/README.md
Labels: needs/ok-to-test, needs/review, size/m

#994 Targetmap Validation
  apis/core/validation/installation.go
  apis/core/validation/installation_test.go
  docs/guided-tour/target-maps/01-multiple-deploy-items/README.md
  docs/usage/TargetLists.md
Labels: needs/ok-to-test, needs/review, size/s

#1002 fix format step
  .ci/format
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#1007 Fix helm deployer for sub charts
  pkg/deployer/helm/deployer.go
  pkg/deployer/helm/ensure.go
  pkg/deployer/helm/helm.go
  pkg/deployer/helm/helm_suite_test.go
Labels: needs/ok-to-test, needs/review, size/s

#1010 upgrade ocmlib
  cmd/landscaper-controller/app/app.go
  cmd/landscaper-controller/app/app_test.go
  cmd/target-sync-controller/app/app.go
  go.mod
  go.sum
  hack/unfold.sh
  pkg/deployer/container/container_suite_test.go
  pkg/deployer/container/garbage_collector_test.go
  pkg/deployer/helm/helm_suite_test.go
  pkg/deployer/lib/cmd/default.go
  pkg/landscaper/controllers/installations/reconcile_delete_test.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl, area/ipcei

#1003 Update guided tour
  docs/guided-tour/README.md
  docs/guided-tour/basics/manifest-deployer/README.md
  docs/guided-tour/basics/multiple-deployitems/README.md
  docs/guided-tour/blueprints/echo-server/README.md
  docs/guided-tour/blueprints/external-blueprint/README.md
  docs/guided-tour/blueprints/external-blueprint/components/component/component-descriptor.yaml
  docs/guided-tour/blueprints/external-blueprint/components/local-blob-component/component-descriptor.yaml
  docs/guided-tour/blueprints/external-blueprint/tour-ctf/artifact-index.json
  docs/guided-tour/blueprints/external-blueprint/tour-ctf/blobs/sha256.91ed47ecd755b10cd7d414badc768c617f88730cee672ba86629b8cb7af256ac
  docs/guided-tour/blueprints/external-blueprint/tour-ctf/blobs/sha256.a237473c060af51b0c884d3984be15cf0772a2f25f84acd9015b0691ebfacc2d
  docs/guided-tour/blueprints/external-blueprint/tour-ctf/blobs/sha256.cb67f21796adcc2856fc57e3bbc58a5135763858d11b182154727323d5847016
  docs/guided-tour/blueprints/helm-chart-resource/README.md
  docs/guided-tour/blueprints/helm-chart-resource/tour-ctf/artifact-index.json
  docs/guided-tour/blueprints/helm-chart-resource/tour-ctf/blobs/sha256.35b1c9420989c501c141dcc901458fee3253929fd814a6c08cf0a87475cb131b
  docs/guided-tour/blueprints/helm-chart-resource/tour-ctf/blobs/sha256.a46de6de5483df2711c2efe8518c48dcc39b92d72803d25bd9bf8c7ef5f0fee7
  docs/guided-tour/blueprints/helm-chart-resource/tour-ctf/blobs/sha256.ccc3f6ffc5cca9a685c1549ed00200cd18bd62ddd126419ef434655553758c23
  docs/guided-tour/target-maps/01-multiple-deploy-items/README.md
  docs/guided-tour/target-maps/02-targetmap-ref/README.md
  docs/guided-tour/target-maps/03-multiple-subinst/README.md
Labels: needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/m

#1011 Fix dependency issues after vendor folder removal
  Makefile
  apis/core/doc.go
  apis/core/v1alpha1/register.go
  apis/core/v1alpha1/types_component_version_overwrite.go
  apis/core/v1alpha1/types_context.go
  apis/core/v1alpha1/types_dataobject.go
  apis/core/v1alpha1/types_deployitem.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/types_installationtemplate.go
  apis/core/v1alpha1/types_ls_health_check.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/types_syncobject.go
  apis/core/v1alpha1/types_target.go
  apis/core/v1alpha1/types_target_sync.go
  apis/deployer/helm/v1alpha1/types_provider.go
  apis/go.mod
  apis/go.sum
  apis/hack/generate-schemes/app/app.go
  apis/hack/generate-schemes/generators/crdgen.go
  apis/hack/generate-schemes/generators/jsonschemagen.go
  apis/hack/generate-schemes/generators/utils.go
  apis/hack/generate-schemes/main.go
  apis/openapi/zz_generated.openapi.go
  apis/schema/schema.go
  controller-utils/go.sum
  docs/api-reference/core.md
  go.mod
  go.sum
  hack/extract-module-version.sh
  hack/generate-code.sh
  hack/tools.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_componentversionoverwrites.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_contexts.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_dataobjects.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_deployitems.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_lshealthchecks.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_syncobjects.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_targets.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_targetsyncs.yaml
Labels: needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/xl

#1016 Check if CRD already exists
  controller-utils/pkg/crdmanager/crdmanager.go
Labels: needs/ok-to-test, needs/review, size/xs

#1017 extract OCM version from go.mod
  Makefile
  hack/extract-module-version.sh
Labels: needs/ok-to-test, needs/review, size/xs

#1021 Inform about panics
  apis/core/register.go
  apis/core/types_critical_problems.go
  apis/core/v1alpha1/register.go
  apis/core/v1alpha1/types_critical_problems.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/zz_generated.openapi.go
  charts/container-deployer/templates/clusterrole.yaml
  charts/helm-deployer/templates/clusterrole.yaml
  charts/manifest-deployer/templates/clusterrole.yaml
  charts/mock-deployer/templates/clusterrole.yaml
  cmd/landscaper-controller/app/app.go
  docs/README.md
  docs/api-reference/core.md
  docs/usage/CriticalProblems.md
  pkg/deployer/container/add.go
  pkg/deployer/helm/add.go
  pkg/deployer/lib/controller.go
  pkg/deployer/manifest/add.go
  pkg/deployer/mock/add.go
  pkg/landscaper/controllers/deployitem/reconcile.go
  pkg/landscaper/controllers/execution/add.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/add.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/targetsync/targetsync_controller.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_criticalproblems.yaml
  pkg/utils/constants.go
  pkg/utils/critical_problems_handler.go
  pkg/utils/panic_handler.go
  pkg/utils/panic_handler_test.go
  pkg/utils/utils_suite_test.go
Labels: needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/xl, area/ipcei

#1042 pin setup-envtest to release-0.16
  Makefile
Labels: needs/ok-to-test, needs/review, size/xs

#1008 integration test refactoring
  .ci/ensure-go
  .ci/ensure-make
  .ci/get_gardener_kubeconfig.py
  .ci/int-test
  .ci/integration-test
  .ci/integration-test-pr
  .ci/integration-test-runner
  .ci/publish-helm-charts
  .ci/testruns/integration-test/Chart.yaml
  .ci/testruns/integration-test/templates/testrun.yaml
  .ci/tm-config.yaml
  .landscaper/components.yaml
  charts/container-deployer/Chart.yaml-e
  charts/helm-deployer/Chart.yaml-e
  charts/laas/charts/resource-cluster/Chart.yaml-e
  charts/landscaper/Chart.yaml-e
  charts/landscaper/charts/landscaper/Chart.yaml-e
  charts/landscaper/charts/rbac/Chart.yaml-e
  charts/manifest-deployer/Chart.yaml-e
  charts/mock-deployer/Chart.yaml-e
  hack/int-test-helper/create-shoot-cluster
  hack/int-test-helper/install-landscaper-dual
  hack/int-test-helper/install-missing-software
  hack/int-test-helper/run-tests
  hack/integration-test.py
  hack/testcluster/pkg/resources/shootcluster_template.yaml
  hack/testcluster/pkg/resources/shootcluster_workerless_template.yaml
  hack/testcluster/pkg/shootcluster_manager.go
  hack/testcluster/pkg/utils.go
  hack/testcluster/shootcluster_create.go
  hack/testcluster/shootcluster_delete.go
  hack/utils.py
  test/framework/framework.go
  test/integration/core/registry.go
  test/integration/dependencies/dependencies.go
  test/integration/deployers/blueprints/blueprints_tests.go
  test/integration/deployers/container/containertests.go
  test/integration/deployers/helmcharts/chartstests.go
  test/integration/deployers/helmdeployer/helm_deployer_tests.go
  test/integration/deployers/manifest_tests.go
  test/integration/importexport/import_data_mappings.go
  test/integration/importexport/import_export.go
  test/integration/importexport/import_validation.go
  test/integration/inline/context.go
  test/integration/inline/inline_blueprints.go
  test/integration/inline/inline_templates.go
  test/integration/rootinstallations/rootinstallations.go
  test/integration/subinstallations/subinstallations.go
  test/integration/targets/targetmaps.go
  test/integration/targets/targets.go
  test/integration/tutorial/aggregated-blueprint.go
  test/integration/tutorial/external-jsonschema.go
  test/integration/tutorial/ingress-nginx.go
  test/integration/tutorial/simple-import.go
  test/utils/resources.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#1043 run make revendor before integration test
  .ci/integration-test-runner
Labels: needs/ok-to-test, needs/review, size/xs

#1046 fix context crd (temporarily disabled openapi spec generation)
  apis/core/v1alpha1/types_context.go
  apis/go.mod
  apis/go.sum
  controller-utils/go.mod
  controller-utils/go.sum
  go.mod
  go.sum
  hack/generate-code.sh
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_contexts.yaml
Labels: needs/ok-to-test, needs/changes, needs/review, size/s, priority/1

#1047 fix make generate step
  .ci/verify
  Makefile
  apis/go.mod
  apis/go.sum
  go.mod
  go.sum
  hack/generate-code.sh
Labels: needs/ok-to-test, needs/rebase, needs/review, size/m
