Repository gardener/landscaper, pull requests merged in 2024-06, with the labels that each got.

#1129 Cache for OCM Contexts
  go.sum
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/registry.go
  pkg/utils/cache/ocm_context_cache.go
Labels: needs/ok-to-test, needs/review, size/m

#1132 Docu for ocm context cache
  docs/technical/installation_controller.md
Labels: needs/ok-to-test, needs/review, size/xs

#1134 Fix link in docu
  docs/guided-tour/basics/manifest-deployer/README.md
  docs/guided-tour/basics/multiple-deployitems/README.md
Labels: needs/ok-to-test, needs/review, size/xs, needs-ok-to-test

#1135 Bugfix ocm config
  charts/container-deployer/templates/clusterrole.yaml
  charts/helm-deployer/templates/clusterrole.yaml
  docs/usage/Context.md
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/landscaper/installations/executions/template/spiff/funcs.go
Labels: needs/ok-to-test, needs/review, size/xs

#1138 bugfix ocm config
  charts/container-deployer/templates/clusterrole.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#1136 test for panic
  test/integration/testdata/tutorial/echo-server/installation-wrong.yaml
  test/integration/tutorial/simple-import.go
Labels: needs/ok-to-test, needs/review, size/s

#1130 Guided tour: component references
  docs/guided-tour/README.md
  docs/guided-tour/subinstallations/component-references/README.md
  docs/guided-tour/subinstallations/component-references/blueprints/root/blueprint.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/root/export-execution.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/root/subinstallation-1.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/root/subinstallation-2.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/root/subinstallation-3.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/sub/blueprint.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/sub/deploy-execution.yaml
  docs/guided-tour/subinstallations/component-references/blueprints/sub/export-execution.yaml
  docs/guided-tour/subinstallations/component-references/commands/component-constructor.yaml
  docs/guided-tour/subinstallations/component-references/commands/component.sh
  docs/guided-tour/subinstallations/component-references/commands/delete-installation.sh
  docs/guided-tour/subinstallations/component-references/commands/delete-other-k8s-resources.sh
  docs/guided-tour/subinstallations/component-references/commands/deploy-k8s-resources.sh
  docs/guided-tour/subinstallations/component-references/commands/settings
  docs/guided-tour/subinstallations/component-references/installation/context.yaml.tpl
  docs/guided-tour/subinstallations/component-references/installation/dataobject.yaml.tpl
  docs/guided-tour/subinstallations/component-references/installation/installation.yaml.tpl
  docs/guided-tour/subinstallations/component-references/installation/target.yaml.tpl
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#1139 Guided Tour: Subinst with templating
  docs/guided-tour/README.md
  docs/guided-tour/subinstallations/component-references/README.md
  docs/guided-tour/subinstallations/export-import/README.md
  docs/guided-tour/subinstallations/general-remarks/README.md
  docs/guided-tour/subinstallations/subinst-templates/README.md
  docs/guided-tour/subinstallations/subinst-templates/blueprints/root/blueprint.yaml
  docs/guided-tour/subinstallations/subinst-templates/blueprints/root/subinst-execution.yaml
  docs/guided-tour/subinstallations/subinst-templates/blueprints/sub/blueprint.yaml
  docs/guided-tour/subinstallations/subinst-templates/blueprints/sub/deploy-execution.yaml
  docs/guided-tour/subinstallations/subinst-templates/commands/component-constructor.yaml
  docs/guided-tour/subinstallations/subinst-templates/commands/component.sh
  docs/guided-tour/subinstallations/subinst-templates/commands/delete-installation.sh
  docs/guided-tour/subinstallations/subinst-templates/commands/delete-other-k8s-resources.sh
  docs/guided-tour/subinstallations/subinst-templates/commands/deploy-k8s-resources.sh
  docs/guided-tour/subinstallations/subinst-templates/commands/settings
  docs/guided-tour/subinstallations/subinst-templates/installation/context.yaml.tpl
  docs/guided-tour/subinstallations/subinst-templates/installation/installation.yaml.tpl
  docs/guided-tour/subinstallations/subinst-templates/installation/target.yaml.tpl
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#1142 aggregate view role also to administrators
  charts/landscaper/charts/rbac/templates/aggregation-clusterroles.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#1140 Blueprint Usage
  docs/usage/Blueprints.md
  docs/usage/Installations.md
Labels: needs/ok-to-test, needs/review, size/m

#1141 Blueprint Cache
  apis/go.sum
  cmd/landscaper-controller/app/app.go
  controller-utils/go.mod
  controller-utils/go.sum
  go.sum
  pkg/components/blueprinthandler_test.go
  pkg/components/cache/blueprint/cache.go
  pkg/components/cache/blueprint/cache_test.go
  pkg/components/cache/blueprint/suite_test.go
  pkg/components/cache/blueprint/testdata/blueprint/blueprint.yaml
  pkg/components/cache/blueprint/testdata/blueprint/test/README.md
  pkg/components/cache/blueprint/testdata/blueprint_edited/blueprint.yaml
  pkg/components/cache/blueprint/testdata/blueprint_edited/test/README.md
  pkg/components/cache/cache.go
  pkg/components/cache/filesystem.go
  pkg/components/cache/inmemory.go
  pkg/components/cache/metrics.go
  pkg/components/cache/types.go
  pkg/components/cnudie/resourcetypehandlers/blueprint/handler.go
  pkg/components/common/util.go
  pkg/components/components_test.go
  pkg/components/ocmlib/ocm_test.go
  pkg/components/ocmlib/resourcetypehandlers/blueprint/handler.go
  pkg/deployer/container/init/init.go
  pkg/deployer/helm/chartresolver/chartresolver_suite_test.go
  pkg/landscaper/blueprints/blueprint_suite_test.go
  pkg/landscaper/blueprints/resolve.go
  pkg/landscaper/blueprints/resolve_test.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/installations/executions/operation_test.go
  pkg/landscaper/installations/executions/template/common/utils.go
  pkg/landscaper/installations/executions/template/gotemplate/funcs.go
  pkg/landscaper/installations/executions/template/gotemplate/gotemplate.go
  pkg/landscaper/installations/executions/template/gotemplate/gotemplate_test.go
  pkg/landscaper/installations/executions/template/options.go
  pkg/landscaper/installations/executions/template/spiff/funcs.go
  pkg/landscaper/installations/executions/template/spiff/spifftemplate.go
  pkg/landscaper/installations/executions/template/template.go
  pkg/landscaper/installations/executions/template/template_test.go
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/installation_imports_and_blueprint.go
  pkg/landscaper/installations/operation_test.go
  pkg/metrics/metrics.go
  pkg/utils/blueprints/blueprint.go
  pkg/utils/cache/ocm_context_cache.go
  pkg/utils/landscaper/blueprint.go
  pkg/utils/landscaper/blueprint_test.go
  pkg/utils/landscaper/installation_simulator.go
  pkg/utils/landscaper/installation_simulator_test.go
  test/utils/resources.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#1145 Document blueprint cache
  docs/technical/installation_controller.md
Labels: needs/ok-to-test, needs/review, size/xs

#1155 chore(deps): upgrade open-component-model/ocm to v0.11.0
  Makefile
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m

#1156 Make repository context in context resource optional
  pkg/landscaper/blueprints/resolve.go
  pkg/landscaper/installations/context.go
Labels: needs/ok-to-test, needs/review, size/xs

#1169 Fix OCM race condition and test
  pkg/components/ocmlib/registryaccess.go
  pkg/landscaper/jsonschema/jsonschema_suite_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#1170 Fix Context Documentation
  docs/usage/Context.md
Labels: needs/ok-to-test, needs/review, size/xs
