Repository gardener/landscaper, pull requests merged in 2024-04, with the labels that each got.

#1048 enhance extract-module-version script
  hack/extract-module-version.sh
Labels: needs/ok-to-test, needs/review, size/xs

#1057 Renovate for makefile
  .golangci.yaml
  Makefile
  apis/go.mod
  apis/go.sum
  controller-utils/go.mod
  controller-utils/go.sum
  go.mod
  go.sum
  hack/install-registry.sh
  renovate.json
Labels: needs/ok-to-test, needs/review, size/m

#1064 Renovate for makefile
  Makefile
  renovate.json
Labels: needs/ok-to-test, needs/rebase, needs/review, size/xs

#1076 fix ready check of deployments (run-int-tests)
  pkg/deployer/lib/readinesscheck/defaultreadinesscheck.go
Labels: needs/ok-to-test, needs/review, size/xs

#1077 upgrade k8s version of integration test cluster (run-int-tests)
  hack/testcluster/pkg/resources/shootcluster_template.yaml
  hack/testcluster/pkg/resources/shootcluster_workerless_template.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#1081 Fix unit tests of readiness checks
  pkg/deployer/lib/readinesscheck/defaultreadinesscheck_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#993 Add OCM Verify to installation
  apis/.schemes/config-v1alpha1-LandscaperConfiguration.json
  apis/config/types_landscaper_config.go
  apis/config/v1alpha1/defaults.go
  apis/config/v1alpha1/types_landscaper_config.go
  apis/config/v1alpha1/zz_generated.conversion.go
  apis/core/types_context.go
  apis/core/types_installation.go
  apis/core/v1alpha1/types_context.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/zz_generated.openapi.go
  docs/usage/SignatureVerification.md
  go.mod
  pkg/components/cnudie/registryaccess.go
  pkg/components/model/registryaccess.go
  pkg/components/ocmlib/registryaccess.go
  pkg/components/testutils/registryaccess.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_contexts.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/utils/verify/utils.go
  pkg/utils/verify/utils_suite_test.go
  test/landscaper/e2e/inlinecd_test.go
  test/landscaper/e2e/simple_test.go
Labels: needs/ok-to-test, needs/rebase, needs/changes, needs/review, needs/second-opinion, size/xl

#1088 Fix scripts of Guided Tour
  docs/guided-tour/basics/manifest-deployer/commands/deploy-k8s-resources.sh
  docs/guided-tour/basics/manifest-deployer/installation/target.yaml.tpl
  docs/guided-tour/basics/multiple-deployitems/commands/deploy-k8s-resources.sh
  docs/guided-tour/basics/multiple-deployitems/installation/target.yaml.tpl
  docs/guided-tour/basics/upgrade/commands/deploy-k8s-resources.sh
  docs/guided-tour/basics/upgrade/installation/target.yaml.tpl
  docs/guided-tour/components/helm-chart/commands/deploy-k8s-resources.sh
  docs/guided-tour/components/helm-chart/installation/target.yaml.tpl
  docs/guided-tour/error-handling/delete-error/commands/deploy-k8s-resources.sh
  docs/guided-tour/error-handling/delete-error/commands/deploy-target.sh
  docs/guided-tour/error-handling/delete-error/installation/target.yaml.tpl
  docs/guided-tour/error-handling/immediate-error/commands/deploy-k8s-resources.sh
  docs/guided-tour/error-handling/immediate-error/installation/target.yaml.tpl
  docs/guided-tour/error-handling/timeout-error/commands/deploy-k8s-resources.sh
  docs/guided-tour/error-handling/timeout-error/installation/target.yaml.tpl
  docs/guided-tour/hello-world/commands/deploy-k8s-resources.sh
  docs/guided-tour/hello-world/installation/target.yaml.tpl
  docs/guided-tour/import-export/export-parameters/commands/deploy-k8s-resources.sh
  docs/guided-tour/import-export/export-parameters/installation/target.yaml.tpl
  docs/guided-tour/import-export/import-data-mappings/commands/deploy-k8s-resources.sh
  docs/guided-tour/import-export/import-data-mappings/installation/target.yaml.tpl
  docs/guided-tour/import-export/import-parameters/commands/deploy-k8s-resources.sh
  docs/guided-tour/import-export/import-parameters/installation/target.yaml.tpl
  docs/guided-tour/target-maps/01-multiple-deploy-items/component/commands/delete-rest.sh
  docs/guided-tour/target-maps/01-multiple-deploy-items/component/commands/deploy-k8s-resources.sh
  docs/guided-tour/target-maps/01-multiple-deploy-items/component/installation/target.yaml.tpl
  docs/guided-tour/target-maps/02-targetmap-ref/component/commands/delete-rest.sh
  docs/guided-tour/target-maps/02-targetmap-ref/component/commands/deploy-k8s-resources.sh
  docs/guided-tour/target-maps/02-targetmap-ref/component/installation/target.yaml.tpl
  docs/guided-tour/target-maps/03-multiple-subinst/component/commands/delete-rest.sh
  docs/guided-tour/target-maps/03-multiple-subinst/component/commands/deploy-k8s-resources.sh
  docs/guided-tour/target-maps/03-multiple-subinst/component/installation/target.yaml.tpl
  docs/guided-tour/target-maps/04-forward-map/component/commands/delete-rest.sh
  docs/guided-tour/target-maps/04-forward-map/component/commands/deploy-k8s-resources.sh
  docs/guided-tour/target-maps/04-forward-map/component/installation/target.yaml.tpl
  docs/guided-tour/templating/components/commands/deploy-k8s-resources.sh
  docs/guided-tour/templating/components/installation/target.yaml.tpl
Labels: needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/m

#1084 Helm chart cache
  apis/core/v1alpha1/constants.go
  apis/core/v1alpha1/helper/helpers.go
  docs/usage/Annotations.md
  docs/usage/Optimization.md
  pkg/deployer/helm/chartresolver/chart.go
  pkg/deployer/helm/chartresolver/chart_cache.go
  pkg/deployer/helm/chartresolver/chartresolver_suite_test.go
  pkg/deployer/helm/helm.go
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
Labels: needs/ok-to-test, needs/changes, needs/review, needs/second-opinion, size/xl

#1099 Improve blueprint intro
  docs/usage/Blueprints.md
Labels: needs/ok-to-test, needs/review, size/s
