Repository gardener/landscaper, pull requests merged in 2024-01, with the labels that each got.

#938 Fix empty schema in exports
  pkg/landscaper/installations/exports/constructor.go
Labels: needs/ok-to-test, needs/changes, needs/review, size/xs

#939 Upgrade gardenlinux
  hack/testcluster/pkg/resources/shootcluster_template.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#942 Fix Nilpointer due to Missing EventRecorder
  pkg/landscaper/operation/operation.go
Labels: needs/ok-to-test, needs/review, size/xs

#935 DI Cache in Executions
  apis/core/types_execution.go
  apis/core/types_shared.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  docs/api-reference/core.md
  hack/testcluster/pkg/shootcluster_manager.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/execution/reconcile_test.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/execution/classification.go
  pkg/landscaper/execution/execution.go
  pkg/landscaper/execution/gc.go
  pkg/landscaper/execution/helper.go
  pkg/landscaper/execution/reconcile.go
  pkg/utils/landscaper/landscaper.go
  pkg/utils/read_write_layer/consts.go
  pkg/utils/read_write_layer/read.go
  test/integration/core/registry.go
  test/integration/deployitems/timeouts.go
  test/integration/executions/generations.go
  test/integration/importexport/import_executions.go
  test/integration/tutorial/external-jsonschema.go
  test/integration/tutorial/ingress-nginx.go
  test/integration/tutorial/simple-import.go
  test/landscaper/e2e/inlinecd_test.go
  test/landscaper/e2e/simple_test.go
  test/utils/controller.go
  test/utils/resources.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#936 Caches for installations
  apis/core/types_installation.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  docs/api-reference/core.md
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/installations/context.go
  pkg/landscaper/installations/imports/conditional_imports_test.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  pkg/landscaper/installations/subinstallations/subinstallations_test.go
  pkg/utils/landscaper/landscaper.go
  pkg/utils/read_write_layer/consts.go
  test/integration/core/registry.go
  test/integration/installations/import-export.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#937 Optimization for siblings
  apis/.schemes/core-v1alpha1-Blueprint.json
  apis/core/types_installation.go
  apis/core/types_installationtemplate.go
  apis/core/types_shared.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/types_installationtemplate.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_installationtemplate.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installationtemplate.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  docs/README.md
  docs/api-reference/core.md
  docs/guided-tour/README.md
  docs/usage/Optimization.md
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/installations/context.go
  pkg/landscaper/installations/context_test.go
  pkg/landscaper/installations/executions/operation_test.go
  pkg/landscaper/installations/helper.go
  pkg/landscaper/installations/imports/constructor.go
  pkg/landscaper/installations/imports/types.go
  pkg/landscaper/installations/reconcilehelper/outdated_test.go
  pkg/landscaper/installations/reconcilehelper/reconcilehelper.go
  pkg/landscaper/installations/reconcilehelper/validation_test.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  pkg/landscaper/installations/trigger.go
  pkg/utils/read_write_layer/read.go
  pkg/utils/read_write_layer/write.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/types_installationtemplate.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installationtemplate.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: needs/ok-to-test, needs/rebase, needs/changes, needs/review, needs/second-opinion, size/xl

#945 Fix template map to cdv2
  pkg/landscaper/installations/executions/template/common/utils.go
Labels: needs/ok-to-test, needs/review, size/xs

#944 Make cache access more robust
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/reconcile.go
Labels: needs/ok-to-test, needs/review, size/xs

#947 fix guided tour typo
  docs/guided-tour/error-handling/delete-error/README.md
Labels: needs/ok-to-test, needs/review, size/xs

#949 create component descriptor with ocm
  .ci/component_descriptor_ocm
  .landscaper/components.yaml
  Makefile
  hack/generate-cd.sh
  hack/update-helm-chart-version.sh
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#952 fix chart dependencies version
  hack/update-helm-chart-version.sh
Labels: needs/ok-to-test, needs/review, size/xs

#933 Updated links for new docu generation
  docs/guided-tour/basics/upgrade/README.md
  docs/guided-tour/blueprints/echo-server/README.md
  docs/guided-tour/blueprints/external-blueprint/README.md
  docs/guided-tour/blueprints/helm-chart-resource/README.md
  docs/guided-tour/hello-world/README.md
  docs/guided-tour/templating/components/README.md
Labels: area/documentation, needs/ok-to-test, needs/review, size/s

#951 Disable periodic reconcile
  cmd/landscaper-agent/app/options.go
  cmd/landscaper-controller/app/app.go
  cmd/target-sync-controller/app/app.go
  docs/technical/performance.md
  docs/usage/Optimization.md
  pkg/deployer/lib/cmd/default.go
Labels: needs/ok-to-test, needs/review, size/m

#955 Investigate strict checks
  cmd/landscaper-agent/app/options.go
  cmd/landscaper-controller/app/app.go
  pkg/deployer/lib/cmd/default.go
  pkg/utils/webhook/webhook.go
Labels: needs/ok-to-test, needs/review, size/s

#958 local blob deployer doc
  docs/guided-tour/blueprints/helm-chart-resource/README.md
  docs/guided-tour/blueprints/helm-chart-resource/assets/components.yaml
Labels: needs/ok-to-test, needs/review, size/s

#957 Improve Helm Deployer Docu
  docs/deployer/helm.md
Labels: needs/ok-to-test, needs/review, size/xs

#953 Improve finished cache
  cmd/landscaper-agent/app/options.go
  cmd/landscaper-controller/app/app.go
  cmd/target-sync-controller/app/app.go
  docs/technical/performance.md
  pkg/deployer/lib/cmd/default.go
  pkg/deployer/lib/controller.go
  pkg/deployer/lib/utils.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/utils/finished_object_cache.go
Labels: needs/ok-to-test, needs/review, size/m

#961 fix effective version in makefile
  Makefile
Labels: needs/ok-to-test, needs/review, size/xs

#956 Further improvements
  apis/.schemes/core-v1alpha1-Blueprint.json
  apis/core/types_execution.go
  apis/core/types_shared.go
  apis/core/v1alpha1/types_execution.go
  apis/core/v1alpha1/types_shared.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  docs/api-reference/core.md
  docs/technical/performance.md
  pkg/landscaper/controllers/execution/reconcile_test.go
  pkg/landscaper/controllers/installations/reconcile_delete.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_executions.yaml
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/execution/execution.go
  pkg/landscaper/execution/gc.go
  pkg/landscaper/execution/reconcile.go
  pkg/landscaper/installations/executions/operation.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
  test/integration/executions/generations.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: needs/ok-to-test, needs/rebase, needs/changes, needs/review, needs/second-opinion, size/l

#965 Set useOCMLib default value to true
  charts/container-deployer/values.yaml
  charts/helm-deployer/values.yaml
  charts/landscaper/charts/landscaper/values.yaml
  charts/manifest-deployer/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#964 Fixed Link in hello world README.md
  docs/guided-tour/hello-world/README.md
Labels: needs/ok-to-test, needs/review, size/xs

#967 Hello World: Include namespace reg note and link
  docs/guided-tour/hello-world/README.md
Labels: needs/ok-to-test, needs/review, size/xs
