Repository gardener/landscaper, pull requests merged in 2024-11, with the labels that each got.

#1257 Fix Unmarshaling of Target Config
  pkg/utils/clusters/shoot_client.go
Labels: needs/ok-to-test, needs/changes, needs/review, size/xs

#1256 Improve Guided Tour
  docs/guided-tour/components/helm-chart/README.md
  docs/guided-tour/hello-world/README.md
  docs/guided-tour/import-export/export-parameters/README.md
  docs/usage/Context.md
  docs/usage/Templating.md
Labels: needs/ok-to-test, needs/review, size/s

#1259 Unauthorized error during GetApiResource
  apis/core/v1alpha1/types_shared.go
  pkg/deployer/lib/resourcemanager/apiResourceHandler.go
Labels: needs/ok-to-test, needs/review, size/xs

#1278 Documentation for the fromYaml templating function
  docs/usage/Templating.md
Labels: needs/ok-to-test, needs/review, size/xs
