Repository gardener/landscaper, pull requests merged in 2024-02, with the labels that each got.

#968 Note about the creation of targets
  docs/guided-tour/hello-world/README.md
  docs/guided-tour/targets/README.md
  docs/guided-tour/targets/resources/clusterrolebinding.yaml.tpl
Labels: needs/ok-to-test, needs/review, size/m

#969 fix nil pointer exception
  docs/guided-tour/blueprints/helm-chart-resource/README.md
  pkg/deployer/helm/chartresolver/chart.go
Labels: needs/ok-to-test, needs/review, size/xs

#970 Handle panics
  controller-utils/pkg/logging/constants/constants.go
  pkg/deployer/lib/controller.go
  pkg/landscaper/controllers/deployitem/reconcile.go
  pkg/landscaper/controllers/execution/controller.go
  pkg/landscaper/controllers/installations/controller.go
  pkg/landscaper/controllers/targetsync/targetsync_controller.go
  pkg/utils/panic_handler.go
  pkg/utils/panic_handler_test.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/logging/constants/constants.go
Labels: needs/ok-to-test, needs/review, size/m

#954 private registry integration test
  go.mod
  go.sum
  test/framework/framework.go
  test/integration/deployers/helmdeployer/helm_deployer_tests.go
  test/integration/deployers/helmdeployer/testdata/01/chart.tgz
  test/integration/suite_test.go
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/layout/gc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/rebase, needs/review, needs/second-opinion, size/m

#966 ocm cleanup
  .ci/component_descriptor
  .ci/component_descriptor_real
  .ci/int-test
  .ci/pipeline_definitions
  .ci/publish-helm-charts
  .landscaper/component-references.yaml
  .landscaper/container-deployer/example/component/component-descriptor.yaml
  .landscaper/container-deployer/example/imports.yaml
  .landscaper/container-deployer/resources.yaml
  .landscaper/helm-deployer/example/component/component-descriptor.yaml
  .landscaper/helm-deployer/example/imports.yaml
  .landscaper/helm-deployer/resources.yaml
  .landscaper/manifest-deployer/example/component/component-descriptor.yaml
  .landscaper/manifest-deployer/example/imports.yaml
  .landscaper/manifest-deployer/resources.yaml
  .landscaper/mock-deployer/example/component/component-descriptor.yaml
  .landscaper/mock-deployer/example/imports.yaml
  .landscaper/mock-deployer/resources.yaml
  .landscaper/resources.yaml
  .landscaper/sources.yaml
  apis/config/v1alpha1/defaults.go
  charts/container-deployer/values.yaml
  charts/helm-deployer/values.yaml
  charts/laas/charts/resource-cluster/Chart.yaml
  charts/laas/charts/resource-cluster/templates/serviceaccount.yaml
  charts/landscaper-agent/values.yaml
  charts/landscaper/charts/landscaper/values.yaml
  charts/manifest-deployer/values.yaml
  charts/mock-deployer/values.yaml
  hack/create-helm-chart.sh
  hack/int-test-helper/create-shoot-cluster
  hack/int-test-helper/install-landscaper
  hack/integration-test.py
  hack/local-integration-test
  hack/local-integration-test-with-cluster-creation
  hack/testcluster/pkg/shootcluster_manager.go
  hack/testcluster/shootcluster_create.go
  hack/testcluster/shootcluster_delete.go
  pkg/deployer/container/helper.go
  test/framework/framework.go
  test/integration/deployers/management/dm_tests.go
  test/landscaper/deployer_blueprints/deployer_blueprint_test.go
  vendor/github.com/gardener/landscaper/apis/config/v1alpha1/defaults.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#971 Improve logging
  pkg/deployer/helm/chartresolver/chart.go
  pkg/deployer/helm/helm.go
  pkg/deployer/helm/realhelmdeployer/real_helm_deployer.go
  pkg/deployer/lib/controller.go
  pkg/deployer/lib/readinesscheck/readiness.go
  pkg/landscaper/installations/executions/operation.go
Labels: needs/ok-to-test, needs/review, size/s

#974 Simplify coding
  apis/core/types_installation.go
  apis/core/v1alpha1/types_installation.go
  apis/core/v1alpha1/zz_generated.conversion.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/zz_generated.deepcopy.go
  apis/openapi/openapi_generated.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  controller-utils/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  docs/api-reference/core.md
  pkg/landscaper/controllers/installations/reconcile.go
  pkg/landscaper/crdmanager/crdresources/landscaper.gardener.cloud_installations.yaml
  pkg/landscaper/dataobjects/imported.go
  pkg/landscaper/installations/generation.go
  pkg/landscaper/installations/generation_test.go
  pkg/landscaper/installations/importstatus.go
  pkg/landscaper/installations/installation_and_imports.go
  pkg/landscaper/installations/operation.go
  pkg/landscaper/installations/reconcilehelper/reconcilehelper.go
  test/landscaper/e2e/inlinecd_test.go
  test/landscaper/e2e/simple_test.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#983 Adding Guided Tour Structure again
  docs/guided-tour/README.md
Labels: needs/ok-to-test, needs/review, size/s

#984 add FromContextOrPanic method to logging library
  controller-utils/pkg/logging/logger.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/logging/logger.go
Labels: needs/ok-to-test, needs/review, size/xs

#985 added frontmatter metadata to Usage Docs
  docs/README.md
  docs/usage/AccessingBlueprints.md
  docs/usage/Annotations.md
  docs/usage/Blueprints.md
  docs/usage/ComponentOverwrites.md
  docs/usage/ConditionalImports.md
  docs/usage/Context.md
  docs/usage/DeployItemTimeouts.md
  docs/usage/Installations.md
  docs/usage/JSONSchema.md
  docs/usage/LandscaperCli.md
  docs/usage/Logging.md
  docs/usage/Optimization.md
  docs/usage/RepositoryContext.md
  docs/usage/SkipUninstall.md
  docs/usage/TargetLists.md
  docs/usage/TargetSyncs.md
  docs/usage/Targets.md
  docs/usage/Templating.md
Labels: needs/ok-to-test, needs/review, size/m

#987 frontmatter added to deployer docs
  docs/README.md
  docs/deployer/README.md
  docs/deployer/container.md
  docs/deployer/healthchecks.md
  docs/deployer/helm.md
  docs/deployer/manifest.md
  docs/deployer/manifest_deletion.md
  docs/deployer/mock.md
Labels: needs/ok-to-test, needs/review, size/s

#975 resource type helmChart
  docs/README.md
  docs/deployer/helm.md
  docs/guided-tour/blueprints/echo-server/config-files/components.yaml
  docs/guided-tour/blueprints/echo-server/config-files/local-blob-components.yaml
  docs/guided-tour/blueprints/helm-chart-resource/README.md
  docs/guided-tour/blueprints/helm-chart-resource/config-files/components.yaml
  docs/guided-tour/blueprints/helm-chart-resource/config-files/local-blob-components.yaml
  docs/guided-tour/import-export/import-parameters/component-descriptor.yaml
  docs/technical/types.md
Labels: needs/ok-to-test, needs/changes, needs/review, size/m

#990 create multiarch images
  .landscaper/components.yaml
  Makefile
  hack/generate-cd.sh
Labels: needs/ok-to-test, needs/review, size/s
