Repository gardener/landscaper, pull requests merged in 2024-09, with the labels that each got.

#1222 Log heap dump automatically
  charts/helm-deployer/templates/clusterrole.yaml
  charts/manifest-deployer/templates/clusterrole.yaml
  cmd/helm-deployer-controller/app/app.go
  cmd/landscaper-controller/app/app.go
  cmd/manifest-deployer-controller/app/app.go
  controller-utils/go.sum
  docs/technical/profiling.md
  go.mod
  go.sum
  pkg/utils/profiling.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l

#1223 Create OCM context only if necessary
  pkg/deployer/lib/controller.go
Labels: needs/ok-to-test, needs/review, size/xs

#1225 Ingress readiness check in integration tests
  hack/int-test-helper/install-landscaper-dual
Labels: needs/ok-to-test, needs/review, size/s

#1224 Update kubernetes and gardenlinux version of test clusters
  hack/testcluster/pkg/resources/shootcluster_template.yaml
  hack/testcluster/pkg/resources/shootcluster_workerless_template.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#1239 fix local linter run
  Makefile
  controller-utils/go.sum
  go.sum
  pkg/landscaper/controllers/targetsync/targetsync_controller.go
  pkg/landscaper/installations/executions/template/common/utils.go
  pkg/landscaper/installations/exports/constructor.go
  pkg/landscaper/installations/installation_imports_and_blueprint.go
  pkg/landscaper/installations/subinstallations/subinstallations.go
Labels: needs/ok-to-test, needs/review, size/s

#1241 add validation support for targetMap type
  apis/core/validation/blueprint_test.go
  apis/core/validation/helper.go
Labels: needs/ok-to-test, needs/review, size/xs

#1243 Remove deprecated secretRef field from Target structure
  apis/core/v1alpha1/targettypes/kubernetes_cluster.go
  apis/core/v1alpha1/types_target_test.go
  pkg/deployer/lib/utils.go
Labels: needs/ok-to-test, needs/review, size/m

#1186 Proposal automation
  docs/proposals/generation-command/01-single-helm/chart/echo-server/Chart.yaml
  docs/proposals/generation-command/01-single-helm/chart/echo-server/templates/deployment.yaml
  docs/proposals/generation-command/01-single-helm/chart/echo-server/templates/service.yaml
  docs/proposals/generation-command/01-single-helm/chart/echo-server/values.yaml
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/command.md
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/config.yaml
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/blueprint.yaml
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/deploy-execution.yaml
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/result/blueprints/blueprint-root/blueprint.yaml
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/result/blueprints/blueprint-root/subinstallation-echo-server-extended.yaml
  docs/proposals/generation-command/01-single-helm/create-blueprint-command/result/component-constructor.yaml
  docs/proposals/generation-command/01-single-helm/create-installation-command/command.md
  docs/proposals/generation-command/01-single-helm/create-installation-command/result/context.yaml
  docs/proposals/generation-command/01-single-helm/create-installation-command/result/dataobject-release.yaml
  docs/proposals/generation-command/01-single-helm/create-installation-command/result/dataobject-values.yaml
  docs/proposals/generation-command/01-single-helm/create-installation-command/result/installation.yaml
  docs/proposals/generation-command/01-single-helm/create-installation-command/result/target.yaml
  docs/proposals/generation-command/01-single-helm/create-installation-command/settings.yaml
  docs/proposals/generation-command/02-double-helm/chart/echo-server-extended/Chart.yaml
  docs/proposals/generation-command/02-double-helm/chart/echo-server-extended/templates/deployment.yaml
  docs/proposals/generation-command/02-double-helm/chart/echo-server-extended/templates/service.yaml
  docs/proposals/generation-command/02-double-helm/chart/echo-server-extended/values.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/command.md
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/config.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/blueprint.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/deploy-execution.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/export-execution.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-next-chart/blueprint.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-next-chart/deploy-execution.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-root/blueprint.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-root/subinstallation-echo-server-extended.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/blueprints/blueprint-root/subinstallation-next-chart.yaml
  docs/proposals/generation-command/02-double-helm/create-blueprint-command/result/component-constructor.yaml
  docs/proposals/generation-command/02-double-helm/create-installation-command/command.md
  docs/proposals/generation-command/02-double-helm/create-installation-command/result/context.yaml
  docs/proposals/generation-command/02-double-helm/create-installation-command/result/dataobject-release.yaml
  docs/proposals/generation-command/02-double-helm/create-installation-command/result/dataobject-values.yaml
  docs/proposals/generation-command/02-double-helm/create-installation-command/result/installation.yaml
  docs/proposals/generation-command/02-double-helm/create-installation-command/result/target.yaml
  docs/proposals/generation-command/02-double-helm/create-installation-command/settings.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/command.md
  docs/proposals/generation-command/03-units/create-blueprint-command/config.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/blueprint.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/deploy-execution.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-echo-server-extended/export-execution.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-next-chart/blueprint.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-next-chart/deploy-execution.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-root/blueprint.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-root/subinstallation-echo-server-extended.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/blueprints/blueprint-root/subinstallation-next-chart.yaml
  docs/proposals/generation-command/03-units/create-blueprint-command/result/component-constructor.yaml
  docs/proposals/generation-command/03-units/create-installation-command/command.md
  docs/proposals/generation-command/03-units/create-installation-command/result/context.yaml
  docs/proposals/generation-command/03-units/create-installation-command/result/dataobject-release.yaml
  docs/proposals/generation-command/03-units/create-installation-command/result/dataobject-values.yaml
  docs/proposals/generation-command/03-units/create-installation-command/result/installation.yaml
  docs/proposals/generation-command/03-units/create-installation-command/result/target.yaml
  docs/proposals/generation-command/03-units/create-installation-command/settings.yaml
  docs/proposals/generation-command/README.md
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#1244 Update OCM Version to v0.15.0 in Makefile
  Makefile
Labels: needs/ok-to-test, needs/review, size/xs
