Repository gardener/landscaper, pull requests merged in 2024-08, with the labels that each got.

#1197 Remove GetCachingIdentity
  pkg/components/model/resource.go
  pkg/components/ocmlib/resource.go
  pkg/components/testutils/resource.go
Labels: needs/ok-to-test, needs/review, size/xs

#1198 better helm validation message
  apis/deployer/helm/v1alpha1/validation/validation.go
Labels: needs/ok-to-test, needs/review, size/xs

#1199 upgrade shoot clusters
  hack/testcluster/pkg/resources/shootcluster_template.yaml
  hack/testcluster/pkg/resources/shootcluster_workerless_template.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#1190 Profiling of landscaper and deployer pods
  cmd/helm-deployer-controller/app/app.go
  cmd/landscaper-controller/app/app.go
  cmd/manifest-deployer-controller/app/app.go
  docs/technical/profiling.md
  go.mod
  go.sum
  pkg/utils/profiling.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/l, status/closed

#1201 improve error in status
  pkg/landscaper/controllers/installations/reconcile.go
Labels: needs/ok-to-test, needs/review, size/s
